### ISSUE TITLE
Getting error while tower-cli ssl 590 protocol

### ISSUE THREAD

**Issue by a31amit** [ansible/tower-cli#122]
Hello, 

I am new ansible tower-cli and installed with pip on my mac laptop, getting below error while running it.

I tried to use it with --insecure and  verify_ssl false in config file, but its still same. If someone can help or point me right directions. Also when i try simple python GET request with requests module, I am getting same error..Not sure how to fix it 

$ tower-cli user list
*** DETAILS: Getting records. *************************************************
GET https://mytower.tempdomain.com/api/v1/users/
Params: {u'page': 1}

SSL connection failed:
EOF occurred in violation of protocol (_ssl.c:590)

Error: Could not establish a secure connection. Please add the server to your certificate authority.
You can run this command without verifying SSL with the --insecure flag, or permanently disable verification by the config setting:

 tower-cli config verify_ssl false

**Comment by AlanCoding** [comment]
This is the same nature as issue #121, in that the SSLError is catching something it is not supposed to. It is different, however, in that not every one of the calls is raising the error. Ideally, the solution to one issue will cover both. This is present in 2.3.0 and after, and we are aiming to release a fix soon.

**Comment by jangsutsr** [comment]
Issue neutralized on the latest release 2.3.2:
* With `verify_ssl` set false:
```
(env) sitan-OSX:~ sitan$ cat .tower_cli.cfg | sed -n /^verify/p
verify_ssl = false
(env) sitan-OSX:~ sitan$ tower-cli user list -v
*** DETAILS: Getting records. *************************************************
GET https://ec2-54-234-179-218.compute-1.amazonaws.com/api/v1/users/
Params: {u'page': 1}

== ======== ================= ========== ========= ============ 
id username       email       first_name last_name is_superuser 
== ======== ================= ========== ========= ============ 
 1 admin    admin@example.com                              true
== ======== ================= ========== ========= ============ 
```
* With `--insecure` flag set:
```
(env) sitan-OSX:~ sitan$ cat .tower_cli.cfg | sed -n /^verify/p
verify_ssl = true
(env) sitan-OSX:~ sitan$ tower-cli user list --insecure -v
*** DETAILS: Getting records. *************************************************
GET https://ec2-54-234-179-218.compute-1.amazonaws.com/api/v1/users/
Params: {u'page': 1}

== ======== ================= ========== ========= ============ 
id username       email       first_name last_name is_superuser 
== ======== ================= ========== ========= ============ 
 1 admin    admin@example.com                              true
== ======== ================= ========== ========= ============ 
```

Closing the issue...
