### ISSUE TITLE
Error: failed to parse some of the extra variables.

### ISSUE THREAD

**Issue by palankai** [ansible/tower-cli#124]
I've installed the version 2.3.1 (latest at the moment), I created an extra var file, but I wasn't able to pass it or extra vars in any way.
Just for the record, from the Ansible Tower, I was able to deploy without issue.

I executed the following command, then I received the error.
```
[jenkins@server ~]$ tower-cli job launch --job-template="[test] deploy" --monitor --extra-vars="build_version: devel_718"
Error: failed to parse some of the extra variables.
variables:
{
	"build_version": "VERSION",
	"env": "test",
	"library_path": "./ansible-playbooks/playbooks/"
}
```

## Details
OS: Amazon Linux (2015.03)
Python: 2.7.9
Ansible Tower 2.1.4
Tower CLI 2.3.1

## Related errors

I received the same error with:
```
[jenkins@server ~]$ tower-cli job launch --job-template="[test] deploy" --monitor --extra-vars="@vars.yml"
```
or even with:
```
[jenkins@server ~]$ tower-cli job launch --job-template="[test] deploy" --monitor
```

## Workaround
**I downgraded to version 2.3.0 and it works well (with @filename format).**

**Comment by AlanCoding** [comment]
I think I can see what's going on here. The variables in the error message contain more than just the --extra-vars you are passing in that command. That means that the rest of them are coming from your job template. We had to combine the local extra-vars with those in the job template inside of tower-cli if the version of Ansible Tower was earlier than 2.4, and this matches what you have.

Thanks for brining this to our attention. I'll look into adjusting the unit test to pick this up, and then it would definitely be in line to go out in the next release.

**Comment by AlanCoding** [comment]
If you still have your configuration available, @palankai , I would be very interested to know if the bug fix branch addresses the problem. Installation with pip from the branch:

```bash
pip install git+https://github.com/AlanCoding/tower-cli.git@124_JT_vars_as_dict
```

I'm not 100% sure this will fix it, but I think there's a good chance.

**Comment by palankai** [comment]
No, it doesn't solved the issue:
```
[root@server ~]# pip install -U git+https://github.com/AlanCoding/tower-cli.git@124_JT_vars_as_dict
[jenkins@server ~]$ tower-cli job launch --job-template="test: name of the job" --monitor --extra-vars="@vars.yml"
Error: failed to parse some of the extra variables.
variables:
{
	"common_library_path": "./ansible-playbooks/playbooks",
	"env": "test",
	"docker_tag": null,
	"private_docker_registry_secret": "Z***************************I="
}
```
Content of vars.yml (I'm sure it doesn't count though)
```
[jenkins@server ~]$ cat vars.yml
docker_tag: eda0ca47
env: test
common_library_path: ./ansible-playbooks/playbooks
private_docker_registry_secret: Z**********************************I=
```

Then downgrade back again:
```
[root@server ~]# pip install -U ansible-tower-cli==2.3.0
[jenkins@server ~]$ tower-cli job launch --job-template="test: name of the job" --monitor --extra-vars="@vars.yml"
===== ============ ======================== ========== =======
 id   job_template         created            status   elapsed
===== ============ ======================== ========== =======
22013         1595 2016-02-23T11:49:38.633Z successful  90.598
===== ============ ======================== ========== =======
```
(The vars and the job is different than as I reported originally, but the server and tower exactly same)

**Comment by AlanCoding** [comment]
Previously, I spun up an Amazon Linux box and tried to reproduce this, and I wasn't able to with a recent version of Tower. I'm going to close this, and if it comes back up we can try again.
