### ISSUE TITLE
Job not starting after update from 2.3.1 to 2.4.4

### ISSUE THREAD

**Issue by matiasdecarli** [ansible/tower-cli#126]
Hi guys. Before the update this was working OK

```
tower-cli job launch --job-template=55 --extra-vars="DIT=2221 BN=9881"
Error: The Tower server claims it was sent a bad request.

POST https://<HOST>/api/v1/job_templates/55/launch/
Params: None
Data: {"extra_vars": "DIT=2221 BN=9881"}

Response: {"variables_needed_to_start": ["'BN' value missing", "'DIT' value missing"]}
```

Am I doing something wrong here? Thanks in advance

**Comment by matiasdecarli** [comment]
Apparently this is the way it works now

```
tower-cli job launch --job-template=19 --extra-vars="{'DIT': 2221, 'BN': 9881}"
```

I hope this helps as a future reference. I believe documentation should be updated

**Comment by AlanCoding** [comment]
I can't reproduce the behavior here from the tower-cli side. Launching a job with those extra_vars gives me a request that contains:

    Data: {u'extra_vars': '{"DIT": 2221, "BN": 9881}'}

I wouldn't be surprised if you saw that behavior if you were using Tower 2.4.4 with tower-cli 2.3.0. You need tower-cli 2.3.1 to correctly use key=value syntax parsing.
