### ISSUE TITLE
RFE - Return Hosts in Groups

### ISSUE THREAD

**Issue by amclean-rh** [ansible/tower-cli#131]
I've got a fairly simple use case.  An inventory with child groups.  I'd like to know what hosts are in those child groups.

I'm able to get the list of child groups in that inventory using:
tower-cli group list --inventory [ID]

However I'm not aware of any way to get the list of hosts in those group IDs.

I would expect that:
tower-cli host list --group [ID] 

Would return me a list of hosts in that group similar to native API call:
/api/v1/groups/[ID]/hosts/

**Comment by AlanCoding** [comment]
You're right. It looks like this just has not been added yet. We just don't have this level of feature parity yet. I can't come up with any good work-around to do this right now, but we will put it on the agenda for a minor release because it should be fairly simple to add.

**Comment by AlanCoding** [comment]
This is very similar to what's done in #135, but host listing might still be left out. You may also be able to do this to list groups in group pk number 2, for example:

> tower-cli host list --query groups__in 2
