### ISSUE TITLE
Can not print a resource's fields

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#144]
This is relevant for anyone using tower-cli as a python library.

Create some resource, like `res = tower_cli.get_resource('foobar')`, then try to inspect `res.fields`. This should be a list, but an error is encountered half way through:

```
[<Field: name (str, unique)>, <Field: description (str, not required)>, *** AttributeError: 'function' object has no attribute 'replace'
```

This appears to be due to the fact that [our custom types](https://github.com/ansible/tower-cli/blob/master/lib/tower_cli/utils/types.py) don't have [a `__name__` attribute](https://github.com/ansible/tower-cli/blob/master/lib/tower_cli/models/fields.py#L71). We should to go through all our custom types and assure that `__name__` is there and that the `__repr__` function works.

It looks like our inherited `ParamType`s from `click` also don't have this stuff, so there may be some potential for contributing upstream.

**Comment by jangsutsr** [comment]
All `__name__` attributes are added to custom types. However there are also external field types that do not have __name__  attribute (like click.Choice). So for now I use `type(self.type).__name__` to represent the name of all field type names. Not sure if it is okay though.
