### ISSUE TITLE
Give indication of "changed" other than color

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#160]
We should provide some other kind of help to the user to inform them whether a record was changed or not. For example, consider the following command:

```
tower-cli user create --username test_user --password pass --email foo@bar.com
== ========= =========== ========== ========= ============ 
id username     email    first_name last_name is_superuser 
== ========= =========== ========== ========= ============ 
10 test_user abc@abc.com                             false
== ========= =========== ========== ========= ============ 
```

In the console, I can see that the color is green in this case, indicating that the record was not changed because this user already existed. However, colorblind users can not see this. Additionally, if the output was piped to any plaintext destination, the coloring would be lost.

I advocate that we provide some sort of explicit notification that the `changed` field is present, and its T/F value.

**Comment by jangsutsr** [comment]
@AlanCoding Since it is impossible to change multiple objects with one operation, does that still make sense to make change a field in a *table*? How about we prepend a line like `Changed: true/false` before the table?

**Comment by AlanCoding** [comment]
> How about we prepend a line like Changed: true/false before the table?

That's what I would prefer, for exactly the reason you mention. I also wonder if we should have a way to turn it off, like with a settings variable.
