### ISSUE TITLE
Allow version to work despite connectivity

### ISSUE THREAD

**Issue by phips** [ansible/tower-cli#185]
Can tower-cli please ...

a) permit 'version' to work even if there's no connectivity...
```
(pip)MBP:~$ tower-cli version
Error: There was a network error of some kind trying to connect to Tower.

The most common  reason for this is a settings issue; is your "host" value in `tower-cli config` correct?
Right now it is: "127.0.0.1".
```
b) permit `--version`, the same as for ansible/ansible-playbook commands

Thanks!

**Comment by jangsutsr** [comment]
@phips Implemented in #188. Will come with tower-cli 3.0.0

**Comment by phips** [comment]
Magic, thanks @jangsutsr!

Does it also work _before_ trying to connect to the tower configure in the .cfg?

**Comment by jangsutsr** [comment]
@phips That's how it works. We reversed the sequence of display tower-cli version and tower version, which internally mean cli's version will be displayed regardless of the state of remote tower server.
