### ISSUE TITLE
Enabling survey and passing extra-vars doesn't work

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/tower-cli#196]
### Summary

If we enable a survey on job template and try to pass the variables as extra-vars from tower-cli it gives an error saying 

Error: The Tower server says you can't make a request with the POST method to that URL (https://tower.example.com/api/v1/job_templates/55/launch/).

### Environment

* Tower version: 3.0.0/ 3.0.1
* Ansible version:  2.1.0.0

### Steps To Reproduce:

1.) Create a job template with a survey.
2.) Try to launch the job with tower cli and pass extra vars for the survey variables

### Expected Results:

Job should get launch with extra vars being passed to survey
### Actual Results:

It throws an error saying:

Error: The Tower server says you can't make a request with the POST method to that URL (https://tower.example.com/api/v1/job_templates/55/launch/).

### Additional Information:

Here is the full verbose log just in case needed.

tower-cli job launch --job-template 55 --verbose --extra-vars="testvar: nikhil"

*** DETAILS: Getting the record. **********************************************
GET https://tower.example.com/api/v1/job_templates/55/
Params: {}

*** DETAILS: Asking for information necessary to start the job. ***************
GET https://tower.example.com/api/v1/job_templates/55/launch/
Params: {}

*** DETAILS: Launching the job. ***********************************************
POST https://tower.example.com/api/v1/job_templates/55/launch/
Data: {u'extra_vars': '{"testvar": "nikhil"}'}

Error: The Tower server says you can't make a request with the POST method to that URL (https://tower.example.com/api/v1/job_templates/55/launch/).

**Comment by AlanCoding** [comment]
I am concerned that the operation here produced a 405 error, and I can not replicate that error on my own. I have seen a similar but different error. Somehow those might come down to the same thing. I'll have to ask you to retest after another the next release of Tower, and it will probably resolve itself.

Thanks for raising this issue!

**Comment by tristanbes** [comment]
I have the exact same issue.
When trying to launch a job with extra parameters, it gives me the:

Error: The Tower server says you can't make a request with the POST method to that URL

**Comment by jctanner** [comment]
This is the traceback that shows up in tower.log ...

```
2016-08-23 19:31:52,876 ERROR    django.request Internal Server Error: /api/v1/job_templates/7/launch/
Traceback (most recent call last):
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/var/lib/awx/venv/tower/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/lib/python2.7/site-packages/awx/api/views.py", line 2231, in post
  File "/lib/python2.7/site-packages/awx/main/models/jobs.py", line 449, in _accept_or_ignore_job_kwargs
TypeError: string indices must be integers
```

**Comment by jctanner** [comment]
The extra vars are being serialized twice (once in parser.py and again in api.py:request). Due to the double serialization, the deserialized data tower attempts to parse is just a string ... hence the index error in the traceback.

To fix this without really looking further into the unit or other aspects of this code ...

```
[root@localhost tower_cli]# git diff
diff --git a/lib/tower_cli/utils/parser.py b/lib/tower_cli/utils/parser.py
index b44b4e6..fddfb16 100644
--- a/lib/tower_cli/utils/parser.py
+++ b/lib/tower_cli/utils/parser.py
@@ -140,7 +140,7 @@ def process_extra_vars(extra_vars_list, force_json=True):
                       header='decison', nl=2)
     if extra_vars == {}:
         return ""
-    return json.dumps(extra_vars)
+    return extra_vars


 def ordered_dump(data, Dumper=yaml.Dumper, **kws):
```

**Comment by AlanCoding** [comment]
I believe that tower-cli will _always_ pass `extra_vars` as a string. Of course, the quotes are escaped as it is included in the request JSON data. Tower 3.0 will allow you to send it as a nested dict, but I have concerns about the behavior of 2.x versions. I think they might break if you give it non-string `extra_vars`, and that's why I discourage the fix in the above comment (although I see how it fixes this current issue). There is a fix coming in the next release of Tower that should resolve this problem. For now, the hack to set `ask_variables_on_launch` to true will have to suffice as a stop-gap measure.

**Comment by tomfotherby** [comment]
I have the same problem since I upgraded to Tower v3.0.1 and I'm eager to apply the patch but unfortunately I can't find the `jobs.py` file to edit. I only find a compiled version (`/usr/lib/python2.7/dist-packages/awx/main/models/jobs.pyc`) which I can't edit. I'm using Ubuntu 14.04.4.

The "Prompt on Launch" idea won't work for us because we trigger the job from a CI pipeline which doesn't have any human interaction.

**Comment by AlanCoding** [comment]
> The "Prompt on Launch" idea won't work for us because we trigger the job from a CI pipeline which doesn't have any human interaction.

I'm not sure why this should be the case with tower-cli. The `--no-input` flag should keep you from dropping into the text editor, and I'm interested to know if there's another problem blocking a stop-gap solution.

**Comment by tomfotherby** [comment]
@AlanCoding  - My mistake, you're right, ticking the "Prompt on Launch" checkbox for the "Extra Variables" section in tower suddenly made the tower-cli command work just fine. THANKS :+1:

**Comment by tomfotherby** [comment]
[Tower v3.0.2 is out](http://docs.ansible.com/ansible-tower/latest/html/installandreference/release_notes.html#ansible-tower-version-3-0-2) - in my testing only the first `extra-vars` is passed to Tower. I've tried the following different syntaxes, without luck:

* `--extra-vars="version=804 rollback=itsokbabynoworries githubuser=tomfotherby"`
* `--extra-vars="version=804" --extra-vars="rollback=itsokbabynoworries" --extra-vars="githubuser=tomfotherby"`
* `--extra-vars="version: 804.1" --extra-vars="rollback: itsokbabynoworries" --extra-vars="githubuser: tomfotherby"`

(only "version: 804.1" gets to Tower)

**Comment by AlanCoding** [comment]
There was a change going from 2.4.5 to 3.0.0 where `extra_vars` are disallowed unless the job template author either specifies "Prompt on Launch" or creates and enables a survey. If a survey is enabled and the "Prompt on Launch" is false, then only the survey variables will be accepted, while non-survey variables will be ignored.

The intent of this change was to avoid giving permissions to job template users that are not obvious to the people who set it up. This information should be in the release notes somewhere, but I can see how it's hard to confirm exactly with the [API guide](http://docs.ansible.com/ansible-tower/2.2.0/html/userguide/job_templates.html). We might do better to describe the specific case for extra_vars, beyond the general rules for prompted and un-prompted variables.

**Comment by tomfotherby** [comment]
@AlanCoding - Aha, this makes sense and is very helpful info - I'll update my surveys. Much appreciated.

**Comment by AlanCoding** [comment]
Based on the feedback, I don't think that there are any continuing problems stemming from this bug. I'll leave a note to elaborate more on variable selection in documentation. We also have ongoing work to alert user to ignored variables.
