### ISSUE TITLE
Feature to download & upload data in Tower

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#197]
The use-case is that someone has data in one Tower server, and wants the ability to save some data locally, and the ability to create new resources in a 2nd Tower server with the same data. The things we might include for this include:
- job template definitions
- credentials
- projects
- inventory
- ...potentially more

The data would be saved to a YAML file, and read from that same file type when creating the resources.

**Comment by wenottingham** [comment]
... and the key context is that normally you create this via the API using 'id' for all of these fields, and you want the exported format to *not* be tied to particular 'id' values.

**Comment by mpeter** [comment]
I was playing around with Golang and writing Terraform Providers, and wrote an Ansible Tower Terraform Provider, which solves this use case (not that it is actually helpful to you).

This allows you to flexibly write down and manage via GIT the entire "state" of a Tower configuration, including how each type relates to the other. Cool things like doing massive changes to jobs/templates/orgs/etc become simple, (via Terraform Modules, for example), moving jobs between groups/user, etc, just handled via the TF configuration. Moving a complex Tower configuration between Tower environments in a controlled way then becomes trivial.

This issue could then be solved by updating the IP address of the Tower API, and re-running Terraform on the host.

There's no documentation, there are several showstopper bugs, but it works, at least for the example.

[Example Config](https://github.com/mpeter/terraform-provider-tower/blob/master/examples/main.tf)
[Terraform Tower Provider](https://github.com/mpeter/terraform-provider-tower/tree/master/tower)
[Go Tower Client API](https://github.com/mpeter/go-towerapi/tree/master/towerapi)

**Comment by AlanCoding** [comment]
Also see as a very old reference https://github.com/jsmartin/tower_populator

**Comment by akcrisp** [comment]
@AlanCoding its not clear to me if this has made it in or not ? I am very interested in the ability to export and import job templates and any associated surveys ideally between different towers.

**Comment by AlanCoding** [comment]
It's not in, no. I have received a heads up that it is in the works. I can't give you any timetable, but once it's up I'll give a shoutout to this issue and the mailing list.

**Comment by akcrisp** [comment]
thanks for the update

**Comment by ryanpetrello** [comment]
@AlanCoding related: https://github.com/ansible/tower-cli/pull/479 ?

**Comment by AlanCoding** [comment]
Yes, @akcrisp #479 address this and was just put up today.

**Comment by akcrisp** [comment]
thanks @AlanCoding

**Comment by ekultails** [comment]
Linking another related issue: https://github.com/ansible/tower-cli/issues/507

**Comment by AlanCoding** [comment]
Releasing feature to PyPI soon.
