### ISSUE TITLE
Is it possible to create an inventory sync schedule with tower-cli?

### ISSUE THREAD

**Issue by nicholas-chia** [ansible/tower-cli#236]
I am trying to create an inventory sync schedule to perform a sync to clean up the inventory daily. How to do this?

**Comment by jainnikhil30** [comment]
@nicholas-chia 

I was able to create an inventory schedule using following, you need to provide the inventory-source id and rrule according to your need. You can find inventory-source id by looking into api at api/v1/inventories/<id>/

tower-cli schedule create --name cloudtest --inventory-source 192 --rrule "DTSTART:20161208T183000Z RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1"

**Comment by AlanCoding** [comment]
The formatting of RRULE strings is kind of brutal. If anyone was interested, they could look into the use examples from the rrule method from the [python-dateutil](https://pypi.python.org/pypi/python-dateutil) library for some automation. It would also be wonderful to add parameters to the tower-cli schedule class in some useful way (like `--repeat=daily` `--start-time=now`), and use those to build the RRULE. It's not high high-priority for me personally, but anyone would be welcome to have a shot at it.

**Comment by nicholas-chia** [comment]
@jainnikhil30 awesome, I managed to create the inventory schedule...thanks so much!

@AlanCoding thanks for the recommendation...current rrules are fine with me now.

**Comment by rashminair90** [comment]
@jainnikhil30 - If I have to create a schedule to run the inventory sync once the inventory is created , how can that be done? I was interested to know rrule to run once as soon as the inventory is created.
tower-cli schedule create --name cloudtest --inventory-source 192 --rrule
