### ISSUE TITLE
Unable to launch job with job_template name

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/tower-cli#237]
### Summary

Setup tower-cli using tower-cli config, now try to launch a job on a different tower host using -h option and giving job template name, it doesnt work, it gives an error. But if we launch the job by giving job template id it works.

### Environment

* Tower version: 3.0.3
* Ansible version:  2.2.0.0
* Tower-cli version: 3.0.2

### Steps To Reproduce:

1.) Configure tower-cli using tower-cli config
2.) Try to launch a job on different tower host other then what you put in config
3.) Try to launch the job using job_template name something like following 

tower-cli job launch -h **** -u **** -p **** --job-template=HelloWorld

### Expected Results:

It should launch the job

### Actual Results:

It doesn't launch the job but gives the following error 

Error: Could not get job_template. The requested object could not be found.

But if the same job_template is launched with id it works:

tower-cli job launch -h **** -u **** -p **** --job-template=7
Resource changed.
==== ============ ======================== ======= ======= 
 id  job_template         created          status  elapsed 
==== ============ ======================== ======= ======= 
1733            7 2016-12-14T10:10:12.868Z pending
==== ============ ======================== ======= =======

**Comment by AlanCoding** [comment]
believed to be solved by #266

**Comment by jangsutsr** [comment]
Issue solved. Patch will ship with 3.1.1 release.
