### ISSUE TITLE
Cannot create local projects using tower-cli

### ISSUE THREAD

**Issue by paprins** [ansible/tower-cli#247]
I'm using `Tower CLI 3.0.3` to create a `manual` project with the following command:

```
$ tower-cli project create --scm-type manual --organization Default --name first-project --local-path 'first-project'

Error: The Tower server claims it was sent a bad request.

POST https://tower.cloudops.vm/api/v1/projects/
Params: None
Data: {"name": "first-project", "scm_type": "", "local_path": "first-project", "organization": 1}

Response: {"local_path":["Invalid path choice."]}
```
I also tried `/var/lib/awx/projects/first-project` as value for `local_path` ... same result (~ yes, the path exists and is readable)

When I create the project using the UI, it succeeds. After I created it manually, and use `tower-cli` to list the project, it show me this:

```
$ tower-cli project list

== ============ ======== ================================================ ================
id     name     scm_type                     scm_url                         local_path
== ============ ======== ================================================ ================
 4 Demo Project git      https://github.com/ansible/ansible-tower-samples _4__demo_project
 9 first-project                                                          first-project
== ============ ======== ================================================ ================
```

**BTW**: when I use the Tower API directly, I get the same result. 

So, am I using incorrect values for `local_path` or is this a bug?

**Comment by AlanCoding** [comment]
I retraced the paths you took, and I'm 95% sure I know what happened.

Check `/api/v1/config/` in your system's current state, and then `project_local_paths` out of that. You will probably find that `first-project` is not in the list.

Tower excludes all paths that are already being used by another project. So the likely story that happened is that you first created the project in the UI and _then_ tried to create it in tower-cli. The same would have happened in reverse, except that the UI wouldn't have shown the option in the dropdown.

I agree this error message is frustrating, given the circumstances. I'll forward that on for consideration as a Tower improvement. I'm fairly sure nothing about this is unique to tower-cli, so I'll close this issue.

Thank you for bringing this to our attention. The feedback is much appreciated!
