### ISSUE TITLE
Provisioning Callbacks

### ISSUE THREAD

**Issue by wtcross** [ansible/tower-cli#249]
As an Ansible Tower user I should be able to utilize the Tower CLI for triggering provisioning callbacks, rather than relying on a script like those distributed with Tower (`request_tower_configuration.{sh,ps1}`). The provisioning callback feature of the Tower CLI should support not only triggering the callback, but also have proper retry logic and other features of the distributed scripts.

**Comment by AlanCoding** [comment]
This will probably be a new `callback` command in the job_template.py file.

I'm not sure exactly what errors we should retry on, because 400 errors don't offer any hope to success on subsequent retries, but we might just catch any error for simplicity, or emulate the example script as-is.
