### ISSUE TITLE
--extra-vars not working anymore

### ISSUE THREAD

**Issue by sebastiangraf** [ansible/tower-cli#276]
In tower-cli 3.1.0 and 3.2.0, creating job_templates with --extra-vars is not working any more:

`tower-cli job_template create --name was85-nets_cote_nightly-dev-netsc-startcluster --job-type run --inventory was85-dev-netsc --project Plattformen-SBB --playbook was85_default_start.yml --machine-credential was85-dev --ask-variables-on-launch False --extra-vars project=nets_cote_nightly --force-on-exists
`
results in a Job Template where the extra-vars is empty. I tried with `--extra-vars {project:nets_cote_nightly} ` which was not working either.

**Comment by AlanCoding** [comment]
Fallout from #216, and collision between the `create` overwrite for the `job_type` parameter with the overwrite of `write` for the `extra_vars` parameter. Although, the exact mechanism by which this collision happened is still unclear to me, it has always been difficult to predict the behavior when using patterns like that.

**Comment by AlanCoding** [comment]
planning to ship fix in 3.1.3 relatively soon.
