### ISSUE TITLE
Global configuration file throws warning when group/other read permissions

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/tower-cli#286]
### Summary
When setting a configuration file for tower-cli with a globe scope, the file generated is only read and writable by the original user. Setting read permissions to the global file then produces warnings at run-time which cannot be turned off.

### Environment

* Tower version: 3.1.1
* Tower-cli version: 3.1.3

### Steps To Reproduce:

1. Create config with a global scope (as root or with sudo):

```
tower-cli config username user --scope=global
tower-cli config password secret --scope=global
```

2. Review permissions for /etc/tower/tower_cli.cfg
3. Switch to a different (or under privileged) user
4. Run `tower-cli config` or test credentials via `tower-cli inventory list` and verify that the global credentials are not accessible
5. Switch back to the original or privileged user and modify /etc/tower/tower_cli.cfg to be readable by group and/or other
6. Jump back to the under privileged user and run `tower-cli inventory list`

### Expected Results:

```
== ============== ============ 
id      name      organization 
== ============== ============ 
 1 Demo Inventory            1
== ============== ============ 
```

### Actual Results:

```
/usr/lib/python2.7/site-packages/tower_cli/conf.py:47: RuntimeWarning: File /etc/tower/tower_cli.cfg readable by group or others.
  .format(fpname), RuntimeWarning)
== ============== ============ 
id      name      organization 
== ============== ============ 
 1 Demo Inventory            1
== ============== ============
```

### Additional Information:

Workaround to remove warning:

1. Navigate to /usr/lib/python2.7/site-packages/tower_cli/
2. Modify conf.py with the following:

Change (lines 44-47):
```
            if (file_permission.st_mode & stat.S_IRGRP) or \
               (file_permission.st_mode & stat.S_IROTH):
                warnings.warn('File {0} readable by group or others.'
                              .format(fpname), RuntimeWarning)
```

To (lines 44-47):
```
#            if (file_permission.st_mode & stat.S_IRGRP) or \
#               (file_permission.st_mode & stat.S_IROTH):
#                warnings.warn('File {0} readable by group or others.'
#                              .format(fpname), RuntimeWarning)
```

**Comment by AlanCoding** [comment]
So the basic idea is that the warning is self-contradictory with the use of a global config file - because there's no way to have this global config file that's not readable by other groups. Presumably we could ship a fix that just selectively doesn't issue the warning if the scope is global.
