### ISSUE TITLE
using as a python library

### ISSUE THREAD

**Issue by parabuzzle** [ansible/tower-cli#297]
Since all the classes are here.. is it possible to document how to use it within a python file as a library?

You kind of mention it in the readme here: "or as a reference for others developing API interactions with Tower's REST API" 

It would be nice to have a little "this is how you import and configure the client inside a python script" I would prefer to just build python scripts to do the interactions I want rather than shell scripts that call python scripts.

**Comment by AlanCoding** [comment]
We have a start on this here:

https://github.com/ansible/tower-cli/blob/master/docs/source/quickstart.rst

This will be hitting Read The Docs soon.
