### ISSUE TITLE
Copy Module is strange

### ISSUE THREAD

**Issue by fwh1990** [ansible/tower-cli#298]
When I shell tower-cli, **copy module** config src=/tmp/hello.txt  (it's mode=0777, and onwer=awx) ,  tower-cli return  

FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/tmp/hello.txt' in expected paths."}

And **synchronize module** has the similar problem (No such file or directory)

However, when I shell ansible-playbook by myself, it works perfectly.

The playbook just like:

- hosts: all
  tasks:
    - name: copy code to machine
      copy: src=/tmp/hello.txt  dest=/web/hello.txt

Environment:
  centos 7
  ansible 2.3.0.0
  tower-cli 3.1.3
  Ansible Tower 3.1.3

It confuse me the whole day. 
Can you help me? Thank you.

**Comment by wenottingham** [comment]
Hi, I believe you're in the wrong repo; this is for `tower-cli`, a python interface to Ansible Tower's REST API.

I think you want the Ansible repo, that would cover the `ansible-playbook` command, the `copy` module, and more.

That repo is at https://github.com/ansible/ansible.
