### ISSUE TITLE
Passing extra vars overrides job template vars

### ISSUE THREAD

**Issue by autero1** [ansible/tower-cli#30]
Passing extra vars with tower-cli overrides job template vars. We have some vars at the inventory level, some at the tower job template and some we would like to pass via tower-cli (jenkins build number in our case). If we pass any extra vars within the tower-cli request, the inventory vars are preserved, while the job template var values are omitted.

**Comment by lukesneeringer** [comment]
Hi @autero1,
This is almost certainly not an issue in tower-cli, but it may be an issue in Tower itself.
Can you e-mail support@ansible.com, and include information like what version of Tower and Ansible you are using?

Thanks!
