### ISSUE TITLE
tower-cli host create

### ISSUE THREAD

**Issue by jruix** [ansible/tower-cli#31]
I'd like to create a new host and add it within an existing group, but I can't find an option to do it. I've tried with the option --group just in case it was missing in the help, but didn't work.

seems that all hosts are created out from any previously created group and there's no way to add them to a group through the command line client. 

Curiously the web interface doesn't allow to create a host if it isn't in a group.

**Comment by laapsaap** [comment]
+1

**Comment by vikas027** [comment]
@jruix  Try these commands in exact order, worked for me. You have to create the group first and then add hosts into it.

```bash
# tower-cli inventory create --name <name_of_inventory> --organization <name_of_organisation>
# tower-cli group create --name <name_of_group> --inventory <name_of_inventory>
# tower-cli host create --name <name_of_host_machine> --inventory <name_of_inventory>
```

**Comment by AlanCoding** [comment]
@vikas027 I think you left out the last step there, unless I'm just not seeing it for some reason. We need this command:

```bash
# tower-cli host associate --host <name_of_host_machine> --group <name_of_group>
```

I'm still going back over the options (UI and API) to see if there are any other creation options missing related to hosts. Regarding this issue, we can add a --group option to the creation of a host, although that would be a just a little bit more work than just adding a field. That may go into the next release. The one thing I'm worried about is whether inventory is a required field when the group is specified. If it is required, then we're not saving the user much effort by combining the two commands. If it isn't required, then this will complicate the implementation.

Thanks for your comments, this feedback is very helpful.

**Comment by jlaska** [comment]
> Curiously the web interface doesn't allow to create a host if it isn't in a group.

@vikas027 More recent releases of Tower do allow you to create hosts that are not associated with any groups.

**Comment by vikas027** [comment]
@jlaska Which version of Tower ? I tried on v2.3, I guess the latest came a day or two ago and that is v2.3.1. Am I right ?

**Comment by jlaska** [comment]
@vikas027 Support for adding a host to the inventory (but not associating with a group), was added in tower-2.2.0.  If you are having problems with that capability, we can help work through any kinks at support@ansible.com.

**Comment by jlaska** [comment]
@jruix I'm going to close this issue out as the capability exists via the command `tower-cli host associate` as @AlanCoding noted.

Thanks for the bug report!
