### ISSUE TITLE
Can't create project of type 'manual'

### ISSUE THREAD

**Issue by ProgrammingAce** [ansible/tower-cli#32]
Using tower-cli, I can't fully setup a manual project. I can create the project, but have to go into the UI to set the 'Playbook Directory'. The missing variable is called 'local_path' in the API, but I don't see how to set that from tower-cli.

I'm able to set up a manual project properly using the API with this command:

curl -H "Content-Type: application/json" --user admin:password -X POST -d '{"name": "ansible", "description": "", "local_path": "ansible", "scm_type": "", "scm_url": "", "scm_branch": "", "scm_clean": false, "scm_delete_on_update": false, "credential": null, "scm_update_on_launch": false, "scm_update_cache_timeout": 0}' http://**URL**/api/v1/projects

**Comment by schwartzmx** [comment]
+1.  Noticed this the other day when trying to automate a new Tower setup using the cli.

**Comment by nitzmahone** [comment]
This should have been fixed by PR #45

**Comment by jlaska** [comment]
Thanks @nitzmahone .  Closing this issue. Please reopen if the problem remains in master.

**Comment by kathyallen-okta** [comment]
ETA on cutting the new version that has this fix? pip upgrade doesn't see it yet.

**Comment by jlaska** [comment]
tower-cli 2.1.1 was just released.  Enjoy!
