### ISSUE TITLE
optionally show `description` field on list command where applicable

### ISSUE THREAD

**Issue by amokan** [ansible/tower-cli#33]
It would be very helpful to show the description field on some resources optionally to the right of the `name` column when doing a `list`. Maybe something like a `-d` parameter?

I have many servers where the name is the IP address and the description is the FQDN.

So I imagine being able to do a `tower-cli host list -d` and it returning something like

id | name | description | inventory | enabled
---|------|-------------|-----------|--------
1  | 1.1.2.2 | foo.bar  | 1 | true
2  | 1.1.2.3 | foo.baz  | 1 | true

**Comment by jangsutsr** [comment]
@amokan This one would be a new feature in 2.4.0.
