### ISSUE TITLE
option for how many results to return

### ISSUE THREAD

**Issue by abraverm** [ansible/tower-cli#339]
`tower job list` returns a long list of jobs, please create an option to modify how many jobs should be listed, for example `tower job list -n 5`.

**Comment by AlanCoding** [comment]
If it helps, we do have the `--all-pages` flag, which will return a list with all records.

This issue comes down to adding a `--page-size` flag for the list commands.

**Comment by abraverm** [comment]
thanks for the workaround, which works nicely with tail, but the flag `--page-size` will be more helpful on the long run.

**Comment by AlanCoding** [comment]
This will go out in 3.1.8 soon
