### ISSUE TITLE
Tower API supports search. Can Tower-cli support this?

### ISSUE THREAD

**Issue by skamithi** [ansible/tower-cli#340]
So for example do

```
tower-cli job_template search "my awesome job"
```
and it will return the appropriate job. In the background it calls
```
https://<tower-url>/api/v1/job_templates/?search=%22my%20awesome%20job%22

```

**Comment by AlanCoding** [comment]
To answer the question, sure, I don't see any problem supporting this. We could add it in the format you propose, which would be some derivative of the list view.

Keep in mind that this can be done now with the `-q` parameter to the list command.

Also, you can search related fields, so one might want that command to allow, for instance, searching by the job template's inventory.

**Comment by skamithi** [comment]
okay I will use the -q option and see how that works. Thanks for the response.
