### ISSUE TITLE
Add command line authentication token option with argument

### ISSUE THREAD

**Issue by jeremyollis** [ansible/tower-cli#341]
Allow previously acquired authentication token, as from the Tower API, to be passed to tower-cli through a command line option and argument.

**Comment by AlanCoding** [comment]
This isn't going to work as expected - the token can only be used by a client that has the same request "hash" as the client that originally requested the token.

This means that if you generate a token from the API browser, you could never use it with tower-cli. Even if you obtained it from a curl command, it probably won't work with tower-cli.

I think what you really want is fully token-based authentication, but this is not available on the Tower side. A request can be filed for official support in Tower, and we can keep this issue around future future tower-cli support of it, whenever and if ever it comes out.

**Comment by AlanCoding** [comment]
This is possible with AWX with `--tower-oauth-token` now.
