### ISSUE TITLE
scm_update_cache_timeout missing from project options

### ISSUE THREAD

**Issue by MichalTaratuta** [ansible/tower-cli#342]
It appears that the setting **scm_update_cache_timeout** is missing from `tower-cli project create ...`

I'm not sure what is this option ``--job-timeout INTEGER           The timeout field (in seconds).``  used for in `tower-cli project create --help`

Anyway `tower-cli project create ...` doesn't allow for specifing the **scm_update_cache_timeout**

**Comment by AlanCoding** [comment]
> I'm not sure what is this option --job-timeout INTEGER The timeout field (in seconds). used for in tower-cli project create --help

If the project update takes longer than the specified time in seconds, then it will be automatically canceled.

**Comment by AlanCoding** [comment]
Staged for near-term release in 3.1.8
