### ISSUE TITLE
Variables: Order of precedence 

### ISSUE THREAD

**Issue by pinduka** [ansible/tower-cli#346]
It would make sense to be able to overwrite any 'core' variable with Tower, so as a developer I can set the default vars in core and then let the user the power to overwrite them in tower. Unfortunately this is not the case currently.
It appears that variables set in core take precedence over the same variables set in tower.

Step to reproduce:

---
# roles/moc_vars/tasks/main.yml
- name: "creating {{ dir_name }}"
  win_file:
    path: "c://{{ dir_name }}"
    state: directory
  when: moc_state == "present"
- name: "removing {{ dir_name }}"
  win_file:
    path: "c://{{ dir_name }}"
    state: absent
  when: moc_state == "absent"

--- 
# moc_vars.yml
- hosts: test_group     
  roles:
     - moc_var

- moc_state is defined as a Tower Job var (to show tower vars are considered)
- dir_name is defined in the locations above with different names to indicate which level is called.

Still, when defining the following, the directory created in the remote host is in_core_group_var:

In Tower (test_group vars) - dir_name: in_tower_group_var
In Core (test_group.yml) - dir_name: in_core_group_var

**Comment by AlanCoding** [comment]
The pattern I most often see is to do something like

```
name: "creating {{ dir_name | default('in_core_group_var') }}"
```

If you wanted to persist the value, you might do best to just `set_fact` using that template syntax.
