### ISSUE TITLE
Problem with SSL: InsecureRequestWarning

### ISSUE THREAD

**Issue by tristanbes** [ansible/tower-cli#35]
I bought a SSL certificate (wildcard domain) to put behind my tower.
When I use `tower-cli` it gives me a warning : 

```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

Tower screenshot : 

![2015-02-13_1601](https://cloud.githubusercontent.com/assets/346010/6189413/b283eb22-b39a-11e4-818d-a8ab2b5e3ed0.png)

**Comment by tristanbes** [comment]
see PR #29

**Comment by flmmartins** [comment]
Hi I am still facing issues.
The verify_ssl argument is not working.
I am on:

Ansible Tower 2.1.3
Tower CLI 2.1.0

**Comment by laapsaap** [comment]
This is annoying, ansible tower here runs on the LAN. We dont bother installing SSL certs for local ip addresses.
