### ISSUE TITLE
Can't list job templates but can launch all of them

### ISSUE THREAD

**Issue by tristanbes** [ansible/tower-cli#36]
As a user, 
I should be able to see available job_templates for me
when I run `tower-cli job_template list `

=> outputs "No records found"

But when I try to launch a job_template : 
`tower-cli job launch --job-template=16`

The job_template is correctly launched (which is ok, because i have the right set of permission), so, why **can't I see it in the listing via the API, but i can launch it** ?

Thanks.

**Comment by vikas027** [comment]
@tristanbes  Try the latest version. I am able to do so.
```bash
# tower-cli job_template list
== ====================== ========= ======= ========
id          name          inventory project playbook
== ====================== ========= ======= ========
 9 Testing first playbook         1       5 dev.yaml
== ====================== ========= ======= ========
#
```

**Comment by jlaska** [comment]
@tristanbes Are you still experiencing this issue?

**Comment by tristanbes** [comment]
nope, fixed on recent releases
