### ISSUE TITLE
Support command-line extra variable option handling similar to ansible-playbook

### ISSUE THREAD

**Issue by tristanbes** [ansible/tower-cli#37]
Why we can't pass extra vars as arguments ? It would ease things : 

yml file as extra vars
1. Jenkins launches the build
2. Jenkins must create a file containing extra vars which will be read by tower-cli 
3. Jenkins calls tower-cli with `tower-cli job launch --job-template 18 --extra-vars ex.yml`
4. Jenkins must erease the file

VS 

inline extra vars
1. Jenkins launches the build
2. Jenkins calls tower-cli with `tower-cli job launch --job-template 18 --extra-vars test:23,site:example.com`

That's just an example, i'm sure there are better options to pass extra vars inline

**Comment by tristanbes** [comment]
Any update on this ?

**Comment by Hefeweizen** [comment]
I'm not commenting on the official implementation.  As a work-around in bash, consider process substitution:   tower-cli job launch --job-template 18 --extra-vars <(echo "{test: 23, site: example.com}")

This is untested, just brain-storming.

**Comment by tristanbes** [comment]
ping @jlaska Any update on this ? Did you discussed it internally ?

**Comment by jlaska** [comment]
Hey @tristanbes.  No update at the moment.  We'll be reviewing outstanding issues with tower-cli and working them into the release cycle soon.

**Comment by tristanbes** [comment]
Ok. Hope it'll be soon then ;)

**Comment by mellowplace** [comment]
:+1:

**Comment by perzizzle** [comment]
I ended up writing a groovy script that interacts with the tower api. This allows you to have parameterized builds in jenkins and add/append this information to your extra_vars. No need for creating files etc... the api is rather straight forward so it wasn't difficult.

**Comment by AlanCoding** [comment]
@tristanbes We are close to implementing this feature, but the syntax is different from the ideas you threw around here, and I just wanted to touch base with you about its usability. Ansible will accept either JSON syntax or the key=value pattern with whitespace between them for the extra_vars. We're going to try to mimic that pattern. For your example, it would be:

tower-cli job launch --job-template 18 --extra-vars "test=23 site=example.com"

In Ansible, you can also indicate a file name with extra variables by putting "@" at the start of the string, and we will do the same. I would imagine that Jenkins users will be able to easily work with this. Do you have any thoughts or comments on this structure?

**Comment by tristanbes** [comment]
@AlanCoding Yes fine by me with ` --extra-vars "test=23 site=example.com"`

Any complex structure would force us to construct it via libraries and string mainpulation, so the easier the simplest.

What happens if the value contains a whitespace ? 
What happens if the value is an array ?

**Comment by jlaska** [comment]
> What happens if the value contains a whitespace ?

I'd recommend using quotes `name="John Smith"`

> What happens if the value is an array ?

I'd recommend not using the `<key>=<val>` syntax for anything more involved than basics numbers/scalars.

**Comment by AlanCoding** [comment]
@tristanbes Here are some test scenarios that will work with this update: in order to pass a list `--extra-vars="a: [1, 2, 3, 4, 5]" `, which is using YAML format. To pass whitespace, `--extra-vars="a='white space'" ` I still need to push another commit, but these cases will be covered in them.

**Comment by tristanbes** [comment]
perfect then :-)
And does the scenario 
```yml
--extra-vars="a: [1, 2, 3, 4, 5] b='white space' "
```

works too ?

**Comment by AlanCoding** [comment]
Yes, your 2nd statement will work. The only problem with your first statement is that you're using 2 different standards together. Here is the same thing reformatted to be a key="value" format:

`--extra-vars='a="[1, 2, 3, 4, 5]" b="white space" '`

This works, and I'll eventually put it in tests too. Ansible, itself, supports extra vars in this syntax so we can say that this type of statement is mostly future-proof.
