### ISSUE TITLE
Change development branch from `master` to `devel`

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#383]
Both Ansible and AWX use `devel` as their primary development branches, so we have no particular justification for using `master` here.

**Comment by jangsutsr** [comment]
If that would be simply a change of default branch name I have no objections, but if we need to do something more I doubt if it is worthwhile. IMO, there seems to be little implication for all our projects to share the same default branch name, especially considering `master` is way more universal for default git branch names.
