### ISSUE TITLE
Incompatibility with AT CLI 3.2 and AT prior 3.2

### ISSUE THREAD

**Issue by my2ter** [ansible/tower-cli#391]
A guess on why it doesn't work, but definitely working when I downgrade to CLI 3.1.8

The CLI is now using **api/v2** which is not present on AT version below 3.2. Unless you are happy with that it should also try the **api/v1**.

With that, all my projects are now throwing:
> Error: Could not get job_template. The requested object could not be found.

Cheers,

**Comment by wenottingham** [comment]
http://tower-cli.readthedocs.io/en/latest/install.html#install-the-right-version

```REST API of Ansible Tower is versioned, and each API version is supported by a subset, rather than all, of ansible-tower-cli versions. Make sure you are pairing your Tower backend with a right version of ansible-tower-cli, specifically:

    If you are using Tower 3.2.0 and beyond, API v2 is available, you should use ansible-tower-cli 3.2.0 and beyond.
    If you are using a Tower version lower than 3.2.0, only API v1 is available, you should use ansible-tower-cli versions lower than 3.2.0.
```
