### ISSUE TITLE
Error: failed to parse some of the extra variables.

### ISSUE THREAD

**Issue by claudio-viola** [ansible/tower-cli#392]
tower-cli version: 3.1.8

tower-cli workflow copy -v ID

OUTPUT
```
GET https://host/api/v1/workflow_job_templates/ID/
Params: {}

Error: failed to parse some of the extra variables.
variables:
{

```
While it works with curl on  ../api/v1/workflow_job_templates/ID/copy

**Comment by AlanCoding** [comment]
Agree that we should swap out the copy method for workflows to POST to `/workflow_job_templates/ID/copy/`. Not all resources have that kind of endpoint, but where it is available, it is preferable.

**Comment by AlanCoding** [comment]
Fix going out in next batch of releases.

We may eventually want to make use of the JT and workflow /copy/ endpoints, but they are not yet fully available in AWX, so I don't want to jump the gun.
