### ISSUE TITLE
Vault credentials cannot be passed to job launch

### ISSUE THREAD

**Issue by viggeh** [ansible/tower-cli#404]
Since Ansible Tower 3.2.0, machine credentials now longer include vault encryption information and have been split into machine credentials and vault credentials.

If you have a job template that needs vault credentials (or other types of credentials), it is not possible to pass the vault credentials with ansible-tower-cli. There seems to be a field called `extra_credentials` in the api that could be used for this.

**Comment by AlanCoding** [comment]
I think you want to use the `vault_credential` field for this. You can apply it to your template here:

https://github.com/ansible/tower-cli/blob/master/tower_cli/resources/job_template.py#L42

The current API does not appear to support `ask_vault_credential_on_launch`, so you would not be able to provide it on job launch. However, I think you can have the vault credential ask to prompt you for your password on launch.

**Comment by AlanCoding** [comment]
I was wrong about the ask_ variable, if you set `ask_credential_on_launch` you can provide the vault credential on launch.

We probably want to add that field to the job launch fields.

**Comment by saurabhrpatil** [comment]
Hi,
   I wish to use vault-password-file feature in tower-cli similar to the implementation in ansible-playbook .
ex:  ansible-playbook xyz.yml  -e "host_group=localhost"  **--vault-password-file=/tmp/pass.txt**

 As of today ,we do not have support for  ask_vault_credential_on_launch in  tower-cli  launch template.
i.e in tower-cli job launch --job-template ..

Can you please let us know by when would this feature be available in tower-cli ?

**Comment by AlanCoding** [comment]
marked for 3.3.8 release
