### ISSUE TITLE
Unable to use tower-cli with AWX

### ISSUE THREAD

**Issue by tchia04** [ansible/tower-cli#439]
By default AWX is setup with http only.
However tower-cli seems to be trying to connect using https

is there anyway to configure tower-cli to use https instead of http? 

Here are the versions I am using
AWX 1.0.1.81
Tower CLI 3.2.0

**Comment by tchia04** [comment]
Never mind. Solve my own issue by reading the code

It turns out you can prepend "http://" to the hostname field to force it to use http instead of the default https

TLDR
    method = click.option(
        '-h', '--tower-host',
        help='The location of the Ansible Tower host. '
             'HTTPS is assumed as the protocol unless "http://" is explicitly '
             'provided. This will take precedence over a host provided to '
             '`tower config`, if any.',
        required=False, callback=_apply_runtime_setting,
        is_eager=True

**Comment by mukadobo** [comment]
AND...

`tower-cli config verify_ssl false`

ALSO, I have the AWX Web-UI bound to an alternate port, so it ends up as

`tower-cli config host http://localhost:20080`
