### ISSUE TITLE
Passing extra vars overwrites tower extra vars

### ISSUE THREAD

**Issue by michaelsharpe** [ansible/tower-cli#44]
I am currently utilizing the tower-cli to launch a job from circleCI.  I have an grunt task to create a file with the build number so my instances can pull down a tarball of the code generated as a build artifact.  

When I use this file as an 'extra-vars' option to pass this build number, it overwrites the extra-vars that I have defined ob my job template on the tower.

Is there any way around this, or a better strategy to take to get the build number from circle ci to the tower?

**Comment by lukesneeringer** [comment]
This is defined by the Tower API behavior, rather than tower-cli.
Can you get the extra vars from the job template, then append the ones you need, and pass the whole thing?

**Comment by tomfotherby** [comment]
Hi @michaelsharpe ,

I had the same problem with Tower CLI 2.1.1. I found I could make a small change to `lib/tower_cli/resources/job.py` and change line 80 from:

    data['extra_vars'] = extra_vars

to

    data['extra_vars'] = data['extra_vars']+extra_vars

In Ubuntu 14.04, this is located at `/usr/local/lib/python2.7/dist-packages/tower_cli/resources/job.py`. 

Once this was done, I could invoke `tower-cli` passing in extra vars using:

    $tower-cli job launch --job-template=48 --extra-vars=<(echo "version: 161")

Hopefully with a future release, such a hack won't be needed.
