### ISSUE TITLE
Environment variable is not working

### ISSUE THREAD

**Issue by tchia04** [ansible/tower-cli#440]
I have some environment variables defined in my ~/.bashrc file
TOWER_HOST=https://localhost
TOWER_USERNAME=nobody

In my ~/.tower_cli.cfg I have the same variable defined with a different value.

However when I run "tower user list" it was still using the settings in my ~/.tower_cli.cfg instead of the environment variable 

According to this page, https://docs.ansible.com/ansible-tower/latest/html/towerapi/towercli.html, the environment variable should override the ~/.tower_cli.cfg file. 

Is this a bug?

**Comment by AlanCoding** [comment]
This will be fixed by the open PR #424
