### ISSUE TITLE
DOC: paging and other options

### ISSUE THREAD

**Issue by alonsocamaro** [ansible/tower-cli#443]
Hi

Could be possible to document how to display a given page? or list them all?

Please this info to http://tower-cli.readthedocs.io/en/latest/cli_ref/index.html

Thanks

**Comment by alonsocamaro** [comment]
I reply to myself. I hope this helps other people trying to figure out how to do this

tower-cli job list --page=<number>

Similary you can filter jobs by status and I suppose than other options listed in the API by using --<option>=<value> 

tower-cli job list --status=running

**Comment by rooftopcellist** [comment]
Hi alonsocamaro,  Thank you for pointing that out.  I have added that to the CLI Reference page in the docs.  (#455)

Thank you for contributing!
Christian
