### ISSUE TITLE
DOC/RFE: is it possible to retrieve a terminated job's log?

### ISSUE THREAD

**Issue by alonsocamaro** [ansible/tower-cli#444]
Hi

I have a job log that cannot be displayed in ansible-tower because it is too large.

Is it possible to retrieve it with tower-cli? After checking the docs... I believe it is not possible 

I didn't find how to retrieve this API. Please document this if it is possible. If it is not available it would be a nice to have. 

Thanks

        Ulises

PS: Is it possible to retrieve directly in the ansible-tower server?

**Comment by alonsocamaro** [comment]
Found the way:

Using a browser go https://<tower Ip address/api/v1/jobs/<job id>/stdout

Then click in the in the small pull down on the right of "GET" and select txt_download

I hope this helps somebody

Regards

      Ulises

**Comment by AlanCoding** [comment]
Right, that endpoint will do the same as the `tower-cli job stdout` command.
