### ISSUE TITLE
issue "ENTER THE SERVER NAME /GROUPNAME"

### ISSUE THREAD

**Issue by amara90** [ansible/tower-cli#447]
Hello guys,

I am beginner with Ansible Tower and I need a solution to run a playbook on specific group.
When I am trying to start a template job, tower ask me "ENTER THE SERVER NAME /GROUPNAME" when I put a groupname Tower doesn't recognize it and run it on host instead the groupname.
Is it already happen to someone?

(picture issue: [https://lh3.googleusercontent.com/-6WkLhETyLII/WhM_ebVZAPI/AAAAAAAAXkA/h5NcjsZ30_4XjoHQRGn8xlQ6lQJb1SCNwCLcBGAs/s1600/issue_tower.PNG]

Thank you

**Comment by AlanCoding** [comment]
The picture you linked to is a survey. Surveys are a tool to help users fill out data that is passed to the playbook run via `--extra-vars`. If you want to target a specific group with your playbook, then you may want to use `--limit` instead, which can be filled out when editing the job template, or set it to prompt on launch.

**Comment by amara90** [comment]
Thank you Alan.
