### ISSUE TITLE
Allow multiple credentials to be set on job_template create

### ISSUE THREAD

**Issue by makesse** [ansible/tower-cli#451]
I am currently trying to create a job template in Tower via tower-cli, and as I need VMWare interaction I would like to add the VMWare credentials to this job.

However, if I only add the VMWare credentials I get the following error:

```
tower-cli job_template create -f id -h $TOWER_HOST -u $TOWER_USER -p $TOWER_PASSWORD -n "VMWare" --project 78 --playbook "main.yaml" --credential 7 --inventory 10
Error: The Tower server claims it was sent a bad request.

POST https://XXX/api/v2/job_templates/
Params: None
Data: {"job_type": "run", "playbook": "main.yaml", "inventory": 10, "credential": 7, "name": "VMWare", "project": 78}

Response: {"credential":["You must provide an SSH credential."]}
```

When I try to add both VMWare and SSH credentials by adding multiple --credential statements only the last one is picked up, and adding a statement like this

`--credential 5,7`

or

`--credential "5 7"`

I get the error that the credential object cannot be found.

I noticed that there is an API call to set extra credentials for a job (which is located at https://XXX/api/v2/job_templates/$JOB_TEMPLATE_ID/extra_credentials/), is it possible to add support for this in tower-cli?

**Comment by makesse** [comment]
FYI, the API call to use when to add additional credentials to a job template (in this case for VMWare credentials) is:

 curl -d '{ "name": "VMWare credentials", "id": 7, "credential_type": 7 }' --user ${TOWER_USER}:${TOWER_PASSWORD} -k -H "Content-Type: application/json" -X POST https://XXX/api/v2/job_templates/$JOB_TEMPLATE_ID/extra_credentials/

I have not found a single API call to create the job template and add the extra credentials.

**Comment by AlanCoding** [comment]
This was added as `tower-cli job_template associate_credential` in #368 

This has not yet been released so that you can pip install it. But soon.

We don't yet have a pattern for associating multiple via `--credential 5,7`, but since the many-to-many fields have been generalized into its own field class, it is technically and logistically possible to add this. The click pattern for "multiple" looks more like `--credential 5 --credential 7`, and that's probably what we would have to use.

**Comment by jangsutsr** [comment]
Closing as 3.2.1 is released.

**Comment by makesse** [comment]
@AlanCoding : thanks, cool!
