### ISSUE TITLE
Allow creation of schedules against a job template specifying an inventory

### ISSUE THREAD

**Issue by grahamneville** [ansible/tower-cli#453]
Hi,

I would like to use tower-cli to be able to schedule runs of a job but against different inventories. It seems this is possible using the following command, but unified-job-template requires an integer which won't be easily known:

```
tower-cli schedule create --name="Schedule against inventory" --unified-job-template="5" --inventory-source="My Inventory 1" --rrule="DTSTART:20171215T000000Z RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1"

Resource changed.
```

If I try this against job_template I can enter the job template's name, but the only option I have is specifying an inventory_source which ends up in an error:

```
tower-cli schedule create --name="Schedule against inventory" --job-template="Demo Job Template" --inventory-source="My Inventory 1" --rrule="DTSTART:20171215T000000Z RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1"

Error: More than one unified job template fields provided, please tighten your criteria.
```

Is there another way I should be doing this? Or can a feature please be added to enable creating a schedule using either a name in unified-job-template, or inventory with job-template?

Thanks

**Comment by AlanCoding** [comment]
Both job templates and inventory sources are "unified job templates", so a schedule either applies to one or the other. Best I can tell, you might want to just specify the inventory source without specifying the job template, like:

```
tower-cli schedule create --name="Schedule against inventory" --inventory-source="My Inventory 1" --rrule="DTSTART:20171215T000000Z RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1"
```

You might have an unrelated issue with multiple results being returned.

**Comment by grahamneville** [comment]
I was hoping that I could schedule a job_template to run against a certain inventory using the schedule options in tower-cli. However this looks to only be able to schedule runs against a schedule that is already setup (unified job template) or an inventory source. 

I was hoping something like this would be possible:

```
tower-cli schedule create --name="Schedule a job against an inventory" --job-template="Demo Job Template" --inventory="My Inventory 1" --rrule="DTSTART:20171215T000000Z RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1"
```

**Comment by AlanCoding** [comment]
> I was hoping that I could schedule a job_template to run against a certain inventory using the schedule options in tower-cli.

If I read that right, I think you're trying to use the functionality that was added very recent in:

https://github.com/ansible/awx/issues/169

The idea is that you can set the job template to prompt for inventory, and then set this inventory with the schedule. If that's the case, then yes, a `--inventory` option is needed for schedules.

If I understood that right, it will be taken care of by #441

**Comment by grahamneville** [comment]
Thanks AlanCoding, that is exactly what I'm after.
The code you mentioned in got added does that work within the UI or is it just with the API at the moment. And is it available in the latest docker image?
If so, how would I go about using the API to create these schedules?

**Comment by AlanCoding** [comment]
You can do this through your browser. Go to `http://yourserveraddress.invalid/api/v2/schedules/<schedule-pk>/`, where you substitute the primary key of your schedule. You'll need to keep track of the inventory primary key as well, and PATCH `{"inventory": <inventory-pk>}` in the browser at that endpoint.

**Comment by grahamneville** [comment]
Thanks AlanCoding, Just tested this and it works fine.
Look forward to being able to set this using tower-cli with a named inventory and schedule rather than the numeric id.

**Comment by AlanCoding** [comment]
That should go out in tower-cli 3.2.2

I'll use this issue to track that

**Comment by AlanCoding** [comment]
going out in 3.3.0 now

**Comment by grahamneville** [comment]
Excellent, thanks @AlanCoding. I've just taken a look at the tower-cli doc's but can't see any use examples for this feature. Are you able to provide some? 
Thanks

**Comment by AlanCoding** [comment]
Sure, we could use something in the CLI guide on this if someone wanted to write it. As things stand now, the issue queue is already pretty large.
