### ISSUE TITLE
Latest version of tower does not have /etc/awx

### ISSUE THREAD

**Issue by kwoodson** [ansible/tower-cli#46]
In order to be compatible with the latest ansible tower version the directory /etc/awx does not exist so therefore we need to update tower-cli in order to keep compatibility.

Inside of tower-cli/conf.py the code still looks for /etc/awx for the .tower_cli.cfg for a global config.  This location does not exist for ansible-tower-2.1.3-1.el7.

global_settings = 'tower_cli.cfg' in os.listdir('/etc/awx/')

**Comment by vikas027** [comment]
I think this has been fixed. When you run the below command, a file `.tower_cli.cfg` gets created in your home directory.

```bash
$ tower-cli config host tower.example.com
$ tower-cli config username leeroyjenkins
$ tower-cli config password myPassw0rd
```
