### ISSUE TITLE
Ansible tower 2.1.4 setup script is broken

### ISSUE THREAD

**Issue by weaseal** [ansible/tower-cli#47]
I tried to upgrade to Ansible Tower 2.1.4 (from 2.1.0).

I downloaded http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-2.1.4.tar.gz

I uncompressed it, cd'd into the directory, ran "./configure --local" which finished successfully, then ran "sudo ./setup.sh" as suggested.  It ran for some time but then died, with this error:

    TASK: [packages_el | install awx RPM] ***************************************** 
    failed: [localhost] => {"changed": false, "failed": true, "rc": 0, "results": []}
    msg: No Package matching 'ansible-tower == 2.1.4' found available, installed or updated
    FATAL: all hosts have already failed -- aborting
    PLAY RECAP ******************************************************************** 
               to retry, use: --limit @/root/site.retry
    localhost                  : ok=22   changed=4    unreachable=0    failed=1   

I was able to work around the issue by manually downloading this file: http://releases.ansible.com/ansible-tower/rpm/epel-6-x86_64/ansible-tower-2.1.4-1.el6.noarch.rpm

And I ran: rpm -Uvh ansible-tower-2.1.4-1.el6.noarch.rpm

Folowed by re-running the "./setup.sh" script - which then succeeded.  Github doesn't seem to want me to attach the .log files, so I have not, please feel free to provide an email address where I can send them, if needed.

**Comment by wenottingham** [comment]
Hi - this repo and issue tracker isn't the support mechanism for Tower - it's for issues specifically with the tower-cli commandline tool.

Please contact support@ansible.com with this information, and we'll help get oyu sorted out there.

Thanks!
