### ISSUE TITLE
Support managing tokens and applications

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#478]
Implement in tower-cli https://github.com/ansible/awx/pull/904

endpoints under `/api/o/`

```
{
    "authorize": "/api/o/authorize/",
    "token": "/api/o/token/",
    "revoke_token": "/api/o/revoke_token/"
}
```

https://github.com/ansible/awx/blob/devel/docs/auth/oauth.md

**Comment by ryanpetrello** [comment]
@matburt @AlanCoding how far do we think we want to go with this?  At least in terms of immediate priority for tower-cli issues, I'm not sure I want to spend time updating `tower-cli` to deal in the actual creation/management of OAuth apps - there's already other plenty of other tools that can be used to interact with OAuth2 endpoints (including the UI in Tower itself).

Do we want to allow people to provide `user+pass+secret_id+secret_key` for an app and generate a token?  Or do we just want to add a flag for specifying a Personal Auth Token?

In my mind, the minimal path to OAuth2 support here is:

1.  Go into Tower and create your app.
2.  `POST` to `/api/o/token/` to generate a personal access token.
3.  Run `tower-cli --oauth-token=<token-value>`

**Comment by AlanCoding** [comment]
I started this issue posting one thing, but here is a different thing.

Both applications and tokens are present as resources under the `/api/v2/` path. These can be added as ordinary resources. This is dead-simple copy+paste and replace kind of effort.

I need to understand more about the standard and the implementation to make any helpful comment on the `/api/o/` endpoints. If I say something now, I will probably be wrong, so this is the end of my comment.

**Comment by matburt** [comment]
There's a lot we can do here, and I think having the oauth2 implementation in Tower/AWX opens up a world of possibilities.

So... most CLI tools use a workflow that works really well with oauth. Look at oc/kubectl for example. You `oc login` give it your username and password and it goes out and fetches your token... stores that instead of your u/p

gcloud will open a browser and let you authenticate that way and pass the token back to the command line tool... this is pretty nifty-keen also since we support ldap/saml/etc. and I believe our 2-legged system would support this kind of thing

**Comment by ryanpetrello** [comment]
@matburt @rooftopcellist I don't _think_ we're currently doing anything to facilitate personal access tokens ala https://github.com/evonove/django-oauth-toolkit/issues/257 (and what @matburt is describing - the notion of user+pass+default app to generate personal tokens).  Do we _want_ to support this in the awx API?  If we don't, the alternative is that `tower-cli` integrators would probably have to provide four things to get an OAuth token:

- auth username
- auth password
- application ID
- application secret

**Comment by matburt** [comment]
We do have an implementation of personal access tokens, but it'll be necessary to allow folks to also supply the application id and secret to not require the use of personal access tokens.

**Comment by ryanpetrello** [comment]
Yep, @rooftopcellist has shown me the way:

```shell
$ curl -ku ryan:ryan -H "Content-Type: application/json" -X POST -d '{"description":"Tower CLI", "application":null, "scope":"read"}' https://awx.example.org/api/v2/users/1/personal_tokens/ | python -m json.tool
```
