### ISSUE TITLE
Examples marked as "deprecated" but nothing to replace it

### ISSUE THREAD

**Issue by calston** [ansible/tower-cli#491]
Guys... come on...

**Comment by ryanpetrello** [comment]
@calston can you elaborate a bit?  We need some context here if we're going to help...

**Comment by AlanCoding** [comment]
They are not deprecated, demonstrated by the fact that I have an open PR to maintain them right now.

What happened was that someone introduced Sphinx docs, but did not migrate the existing docs to the source tree that gets built for Read The Docs.
