### ISSUE TITLE
Creating permissions through Tower CLI

### ISSUE THREAD

**Issue by mikeycmccarthy** [ansible/tower-cli#51]
We'd love to be able to create permissions through Tower CLI. Our playbooks to bootstrap Tower are a mix of CLI calls and API calls. Creating permissions (and other objects) is fine through the API (really liking the browseable documentation) but there are far more steps to do something idempotent in true Ansible style (lookup the permission, POST if not there, PUT if there etc vs just a tower-cli --force-if-exists). 

Thanks!

**Comment by kathyallen-okta** [comment]
"me too"

**Comment by npolonski** [comment]
Which version of tower-cli will this be available in? 
I have 2.3.1 from pip and I don't see permissions as an option

**Comment by wenottingham** [comment]
We're currently working on some not insignificant permissions changes in Tower itself...  this feature will surface in tower-cli after that.
