### ISSUE TITLE
Add multiple Vault-type credentials on creation of new Job Template

### ISSUE THREAD

**Issue by watsonb** [ansible/tower-cli#525]
When using `tower-cli job_template create` there is no known way to add multiple `vault-credential` to the template.  To date, I have tried multiple `--vault-credential "<cred_name>"` arguments and the template simply uses the last specified argument.  I've also tried a comma-delimited list in a single argument (e.g. `--vault-credential "<cred1_name>,<cred2_name>"`, but it errors as it cannot find a single credential matching  the combination of the names.

Given that Ansible 2.4+ supports multiple vaults, I need a method to add the vaults to the job template at create time.  The AWX GUI does allow you to specify multiple vault credentials by clicking the Search icon next to the Credential field, filtering by Vault type, and checking multiple credential items in the list.

**Comment by Yiadh** [comment]
I am facing the same problem. Did you find the solution?

**Comment by Yiadh** [comment]
@AlanCoding could you help as please

**Comment by watsonb** [comment]
@Yiadh , no, we haven't been using AWX as much these days but will likely get back into it at some point.

**Comment by AlanCoding** [comment]
should be in released 3.3.7
