### ISSUE TITLE
Make organization a mandatory field while creating a project

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/tower-cli#530]
On UI, organization is a mandatory field for a project. You can't save the project without assigning it a organization. But tower-cli allows to create a project without organization, which in turn messes up the permission on the job templates based on that project.

You can create a project like following:

~~~
tower-cli project create -n tower-cli-project --scm-type manual --local-path test_tower_cli
~~~

This will create a project names tower-cli-project on Tower without any organization.

After this create a job template based on above project project:

~~~
tower-cli job_template create -n test-tower-cli --project tower-cli-project --playbook test_module.yml --ask-inventory-on-launch true --ask-credential-on-launch true
~~~

This creates a job template named test-tower-cli on Tower. But if you check the permission tab, there is only a Admin permission for the user who created it. All the other System Admins will not show up there. 

This is because there is no organization in the Project. Once I put an organization in the project and recreate the job templates from tower-cli, I see the right permissions.

**Comment by AlanCoding** [comment]
I'm tempted to classify this as a server bug. The OPTIONS and the server behavior tell us that the field is not required.

**Comment by AlanCoding** [comment]
Filed in AWX. tower-cli will make the field required with the API does.
