### ISSUE TITLE
Can't use tower-cli on travis

### ISSUE THREAD

**Issue by tristanbes** [ansible/tower-cli#55]
On the documentation you state that you can use tower cli to launch job templates on ci (like travis)

The problem is that we can't install tower-cli without being sudo.
If using sudo, we break travis and it force us to be on the non-container infrastructure which is old and slow.

Installing via pip with the container infrastructure (sudo: false) results in : 
```
$ pip install ansible-tower-cli
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting ansible-tower-cli
  Downloading ansible-tower-cli-2.1.1.tar.gz
Collecting click>=2.1 (from ansible-tower-cli)
  Downloading click-4.1-py2.py3-none-any.whl (62kB)
    100% |################################| 65kB 5.4MB/s 
Collecting colorama>=0.3.1 (from ansible-tower-cli)
  Downloading colorama-0.3.3.tar.gz
Collecting dict.sorted==1.0.0 (from ansible-tower-cli)
  Downloading dict.sorted-1.0.0.tar.gz (106kB)
    100% |################################| 110kB 4.1MB/s 
Collecting requests>=2.3.0 (from ansible-tower-cli)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |################################| 471kB 1.1MB/s 
Collecting six>=1.7.2 (from ansible-tower-cli)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six, requests, dict.sorted, colorama, click, ansible-tower-cli
  Exception:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/commands/install.py", line 347, in run
      root=options.root_path,
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_set.py", line 549, in install
      **kwargs
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_install.py", line 754, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/req/req_install.py", line 963, in move_wheel_files
      isolated=self.isolated,
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/wheel.py", line 234, in move_wheel_files
      clobber(source, lib_dir, True)
    File "/usr/local/lib/python2.7/dist-packages/pip-6.0.8-py2.7.egg/pip/wheel.py", line 212, in clobber
      shutil.copyfile(srcfile, destfile)
    File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
      with open(dst, 'wb') as fdst:
  IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/six.py'
```

**Comment by jlaska** [comment]
The problem observed is not a problem with `ansible-tower-cli`.  The issue you are seeing is caused by attempting to install pip packages in a system-wide location as a non-privileged user.

If you want to install pip packages in a system-wide location, you will need appropriate privileges (e.g. `root` or another suitably privileged user).

If you want to install pip packages locally, without requiring root privileges, you might consider using https://virtualenv.pypa.io/en/latest/.  Typically with travis, you're using either `tox` or `virtualenv` to manage dependency installation.

**Comment by jlaska** [comment]
@tristanbes Out of curiosity, are you able to share your `.travis.yml` to see how you are installing tower-cli?

**Comment by tristanbes** [comment]
Ofc, if you can provide me a working example without using sudo for travis, would be awesome: 

```
language: php

sudo: false

php:
    - 5.5

after_success:
    - "pip install ansible-tower-cli"
    - "sh ci/release.sh"
```

**Comment by jlaska** [comment]
@tristanbes Thanks for sharing.  I've never seen a `.travis.yml` where the `pip install ...` is outside of the `install:` stmt.  I'm more accustomed to the following (for python-based projects):

```
language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install ansible-tower-cli
script:
# ... do your build stuff
```

In this situation, sudo is not required.

From the travis docs, it appears you'll need to use `sudo` in your situation.  Refer to http://docs.travis-ci.com/user/customizing-the-build/#Installing-Packages-Using-apt  ..

```
before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -qq [packages list]
```

**Comment by tristanbes** [comment]
Well well, I don't want to loose build speed, so sudo is out of question for me. I guess i'll end up using the curl version (which btw are not up-to-date on the documentation (https://support.ansible.com/hc/en-us/articles/201958027-Launching-Jobs-with-curl) 

The reason that the install was made outside the install part is that I need tower-cli only if tests and build are green ;-) not otherwise. Don't want to loose precious seconds on xx builds / day. ;-)

**Comment by jlaska** [comment]
@tristanbes If you want to install a package during your build, you'll unfortunately need to incur the cost of installing at some point.  I can't see `sudo` chewing up much time, compared to the cost of network speed downloading and resolving dependencies.  If you are averse to using `sudo`, you could install locally using `virtualenv` and use that in your `ci/release.sh` script.  However, I suspect `sudo` would still be faster.

Good luck!

**Comment by tristanbes** [comment]
Thanks for your answers. 
FYI, it's not about sudo itself, it's about sudo and Travis: http://docs.travis-ci.com/user/workers/container-based-infrastructure/ I don't know if I made myself clear about that.

**Comment by jlaska** [comment]
@tristanbes  Ah, I see.  It appears travis-ci doesn't support the use of system-wide package installation in their container-based workers (http://docs.travis-ci.com/user/installing-dependencies/#Installing-Ubuntu-packages).  It appears there is a container-based add-on that allows the user of `apt` (http://docs.travis-ci.com/user/apt/).  However, I don't see a similar `pip` add-on.

In the meantime, you'll either need to use `virtualenv tower-cli && ~/path/to/venv/bin/activate && pip install ansible-tower-cli && ci/release.sh`.  Or you'll have to interact with the Tower API using `curl` or the ansible `uri` module.

There appears to be another workaround offered suggested here -> https://github.com/travis-ci/travis-ci/issues/3563

**Comment by tristanbes** [comment]
Awesome, that what I needed ;-)
Thanks.
