### ISSUE TITLE
scheduling workflows fails because they cannot be found

### ISSUE THREAD

**Issue by tumbl3w33d** [ansible/tower-cli#570]
tower-cli version: 3.3.0
tower (awx): 1.0.6.25

I'm trying to schedule a workflow template like this (I removed the host, username and password arguments from all snippets).
```
tower-cli schedule create --force-on-exists -n nightly_backup_mattermost --job-template mattermost_backup --rrule 'DTSTART;TZID=Europe/Berlin:20180712T000500 RRULE:FREQ=DAILY;INTERVAL=1'
```
and I get the result
`Error: Could not get job_template. The requested object could not be found.`
So I check whether it exists by using
`tower-cli job_template list`
and notice it's not in that list, because it's a workflow template. It is included in the output of
`tower-cli workflow list`

I tried several argument combinations to create a schedule for a workflow template, but I didn't find any working combination. Any hint or is this a bug?

**Comment by AlanCoding** [comment]
Oh yeah, it just needs to be added

https://github.com/ansible/tower-cli/blob/71de9de6676c750dcf4d2253cdf0cee01571c343/tower_cli/resources/schedule.py#L105-L113

**Comment by tumbl3w33d** [comment]
Dear @AlanCoding this fix either didn't make it into the 3.3.1 release or it didn't solve the problem.

I use
```
# tower-cli --version
Tower CLI 3.3.1
```
and get the same results as originally described.

**Comment by AlanCoding** [comment]
I believe you need to form the option like `--workflow-job-template mattermost_backup` in the above example.

**Comment by tumbl3w33d** [comment]
This gives me
```
Usage: tower-cli schedule create [OPTIONS]
Try "tower-cli schedule create --help" for help.

Error: no such option: --workflow-job-template
```

**Comment by AlanCoding** [comment]
oh, sorry, it looks like the option is `--workflow`

**Comment by tumbl3w33d** [comment]
Excellent, that works. Thank you so much!
