### ISSUE TITLE
Improve documentation about usage of variables?

### ISSUE THREAD

**Issue by stefan-wegener** [ansible/tower-cli#574]
I am new to tower-cli (I wanted to use it inside a python-script) and really had some struggle to understand how I am able to add variables e.g. when creating a new host.

I ended up searching through the source-code of this repo to find examples where variables get used and finally was successful by adding them to a host. 

Afterwards I was asking myself if I was the only one who did not know how to declare variables e.g. when creating hosts because there was no information about this topic in the documentation? I think everything else of the API is really intuitive or described inside of the documentation, but adding variables is not. 

I am willing to add this additional documentation infomation as a PR, but only if you think that it is a good idea. I probably would add it under "API reference/introduction".

**Comment by AlanCoding** [comment]
This looks like it's the same root issue as 564, and it really comes down to the fact that tower-cli has some variables processing to help, but that was not applied to host variables. It should be much easier and more self-documenting if we just change the type of that field. The concerns are not breaking people using the command in its existing form, and if we might break the call pattern of the tower_host module in Ansible. Still, I think this should be done and it's pretty minor to accomplish.
