### ISSUE TITLE
stdout capture is missing

### ISSUE THREAD

**Issue by jhampson-dbre** [ansible/tower-cli#587]
- Ansible 2.4.3.0
- Tower 3.2.2
- Tower CLI 3.2.1
- Python 3.6.5

We are running a Tower cluster. When I submit jobs from tower-cli with --monitor flag, I usually receive the message `stdout capture is missing` at the end of the job run. If I re-run the same command multiple times, occasionally tower-cli will display the job output as expected.

```
$ tower-cli job launch --job-template=1791 --monitor --limit canary --extra-vars "tfs_buildid=$buildId tfs_artifact_name=$artifactName" --tower-username "$towerUser" --tower-password "$towerPass" --tower-host "$towerHost"
Current status: running
------Starting Standard Out Stream------
stdout capture is missing------End of Standard Out Stream--------
c:\python3\lib\site-packages\tower_cli\conf.py:67: RuntimeWarning: File C:\Users\<username>\.tower_cli.cfg readable by group or others.
  .format(fpname), RuntimeWarning)
Error: Job failed.
```
Viewing the job details from a browser, it displays the full playbook output including the reason for the job failure.

**Comment by AlanCoding** [comment]
kind of related to https://github.com/ansible/tower-cli/issues/571, might be tacked together

**Comment by theDeployinator** [comment]
I noticed this in the Ansible Tower [docs ](https://docs.ansible.com/ansible-tower/latest/html/towerapi/launch_jobtemplate.html) while trying to research the issue:

> When querying a job on a non-execution node, an error message, stdout capture is missing displays for the result_stdout field and on the related stdout page. In order to generate the stdout, use the format=txt_download query parameter for the related stdout page. This generates the stdout file and any refreshes to either the job or the related std will display the job output.

Since our Tower is clustered and the output will intermittently display eventhough the output length is constant, it feels like we may be hitting the scenario described in the docs (i.e. the job ends up being queried on a non-execution node).

**Comment by AlanCoding** [comment]
yeah, that should definitely be fixed in the newest AWX, it's unfortunate that people are still hitting it in the wild. Some way to leverage the download option with the stdout command could be a possible workaround.

**Comment by theDeployinator** [comment]
I think even with the download option, the value tower-cli gets back for result_stdout is "stdout capture is missing". The only way I've been able to get it to consistently retreive the full stdout is to add the format=txt_download query parameter and query the Job Stdout endpoint directly. It works, but it is not as elegant as being able to use the tower-cli monitoring functionality.

```
new_job = get_resource('job').launch(job_template=1791, limit='canary', extra_vars=["tfs_buildid: 281", "tfs_artifact_name: Scripts"])
get_resource('job').wait(new_job['id'])

new_job = get_resource('job').status(new_job['id'], detail=1)

url = "https://towerha.myhost.net/api/v2/jobs/{}/stdout/?format=txt_download".format(new_job['id'])
headers = {'Authorization': 'Basic <password>'}

r = requests.get(url, headers=headers, verify=False)

print(r.text)
print(new_job['status'])
```

**Comment by jhampson-dbre** [comment]
We haven't seen this issue reccur for some time now. Currently running Ansible 2.9, Tower 3.7.1, and tower-cli 3.3.9. I think we can close this.
