### ISSUE TITLE
Clarify support matrix of tower-cli vs. Tower version

### ISSUE THREAD

**Issue by ericzolf** [ansible/tower-cli#597]
What I means with this is, of course, not real support but just which version of tower-cli works against which version of Tower (or AWX) under which limitation, and what the testing strategy is in regard to this.

The kind of statements I mean for example (not saying it is today like this, but a clarification in this direction would be good):

- `tower-cli copy --new-name` doesn't work against Tower 3.2 but only 3.3
- tower-cli X.Y is being automatically tested against, Tower X.Y and X.Y-1, AWX 1.Y, etc...
- as long as the right API version (v2) is used, certain options might fail but without breaking anything in Tower.

Thanks, Eric

**Comment by AlanCoding** [comment]
Thanks, we should do this. This is unique behavior specific to this one command. See:

https://github.com/ansible/tower-cli/blob/2c115877a36238b94fb8af1ff32915ebaf868e60/tower_cli/models/base.py#L635

This should call out the fact that API-backed copy was only introduced in 3.3, so using the option requires that version.
