### ISSUE TITLE
tower-cli setting modify SESSIONS_PER_USER -1 "Error: no such option: -1"

### ISSUE THREAD

**Issue by sonjz** [ansible/tower-cli#601]
The command `tower-cli setting modify SESSIONS_PER_USER -1` doesn't seem to work, setting -1 in the GUI works fine, but if you want to set the "disable" setting, you can't do it from tower-cli.

**Comment by jainnikhil30** [comment]
I dont think this is a a bug, you should be able to set it as
```
tower-cli setting modify AUTH_TOKEN_PER_USER -- -1
```

http://click.pocoo.org/6/arguments/#option-like-arguments
