### ISSUE TITLE
Unable to associate multiple vault credentials to a job_template

### ISSUE THREAD

**Issue by Yiadh** [ansible/tower-cli#609]
Tower CLI 3.3.0
API v2
AWX 1.0.4.14
Ansible 2.4.3.0

How can a associate multiple valt credentials (with different vault identifiers) to the same job template?

When I made:
tower-cli job_template modify --name JobTemplateName --vault-credential valut1 --vault-credential valut2
only vault2 has been taken into consideration

**Comment by AlanCoding** [comment]
Addressing in https://github.com/ansible/tower-cli/issues/525

I don't know if we can remove this function of `--vault-credential`, because of backward-compatibility concerns with older Tower versions. A warning would be workable.
