### ISSUE TITLE
job_events 

### ISSUE THREAD

**Issue by tobiasjohanssonsdnit** [ansible/tower-cli#621]
I find no way to access the job_events "/api/v2/jobs/{id}/job_events/" via the tower_cli, is this possible?

If this is not available, I would like to request this as a feature.

**Comment by AlanCoding** [comment]
Yes, this went out in 3.3.0 https://github.com/ansible/tower-cli/issues/401

it's not shown in the main help text, but you can use it with `tower-cli job_event`

**Comment by tobiasjohanssonsdnit** [comment]
Thanks works
