### ISSUE TITLE
travis-ci fails on master branch

### ISSUE THREAD

**Issue by mwiora** [ansible/tower-cli#637]
currently all travis-ci builds fail
https://travis-ci.org/ansible/tower-cli/jobs/462856823

`=================================== FAILURES ===================================
_________________________ LoginTests.test_no_arguments _________________________
self = <tests.test_cli_misc.LoginTests testMethod=test_no_arguments>
    def test_no_arguments(self):
        """
        Establish that if `tower-cli login` is called with no arguments, it
        complains
        """
        # Invoke the command.
        result = self.runner.invoke(login)
    
        # Ensure that we got a non-zero exit status
        self.assertNotEqual(result.exit_code, 0)
>       self.assertIn('Missing argument "username"', result.output)
E       AssertionError: 'Missing argument "username"' not found in u'Usage: login [OPTIONS] USERNAME\nTry "login --help" for help.\n\nError: Missing argument "USERNAME".\n'
tests/test_cli_misc.py:293: AssertionError
===================== 1 failed, 358 passed in 3.74 seconds =====================
ERROR: InvocationError for command '/home/travis/build/ansible/tower-cli/.tox/py27/bin/coverage run -m pytest -v' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
The command "tox" exited with 1.`

Maybe there is a chance to fix that, since any PR will look not so nice and is hard to verify....
Cheers and thanks,
Matthias

**Comment by AlanCoding** [comment]
I'm fairly sure it's passing again. There is some nastiness related to config management in the tests, but I don't think it's surfacing at this particular moment.
