### ISSUE TITLE
Documentation is wrong: make install in tower_cli does not work

### ISSUE THREAD

**Issue by archmangler** [ansible/tower-cli#639]
- git clone https://github.com/ansible/tower-cli.git
- cd tower-cli/tower_cli
- make install results in error:

```
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by kfattig** [comment]
I had the same problem initially, you're a directory too 'deep'.  Having a directory name that matches the repo name is a little confusing.

This works for me:
```
git clone https://github.com/ansible/tower-cli.git
cd tower-cli
make install
```

**Comment by AlanCoding** [comment]
Some arguments for this layout: https://github.com/ansible/tower-cli/pull/250
