### ISSUE TITLE
Page Numbers incorrect when using all-pages and format human

### ISSUE THREAD

**Issue by kfattig** [ansible/tower-cli#650]
When ``--all-pages`` is specified with ``--format human``, incorrect page numbers are printed.

Sample:
`` tower-cli user list --all-pages``

Returns (most output snipped):
`(Page 1 of 8.)`

This appears to have been introduced [here](https://github.com/ansible/tower-cli/commit/d3f2a8ba937afc11768817a74d6201bf271b6bbb).  Including 'count' broke the logic used to [calculate the current page](https://github.com/ansible/tower-cli/blob/867164ed42a3a28d953cb005b70c601d874f5f20/tower_cli/cli/resource.py#L266).  Prior to this change, no page information was printed when --all-pages is specified.

**Comment by AlanCoding** [comment]
confirmed bug.
