### ISSUE TITLE
tower-cli login does not support username starting with a dash "-"

### ISSUE THREAD

**Issue by nicolasproton** [ansible/tower-cli#671]
Tower CLI 3.3.2
API v2
Ansible Tower 3.4.1
Ansible 2.4.2.0

I have some generic users (used for automation) where the name starts with a dash "-" (not my idea, but a company policy). For exampe, when I run `tower-cli login '-my-id'` it fails with the following error:
```
Usage: tower-cli login [OPTIONS] USERNAME
Try "tower-cli login --help" for help.

Error: no such option: -m
```
Escaping the `-` does NOT work either as the `\` is passed to the rest call.
As a workaround, I stored the username/password in the .tower-cli.cfg. However, I would like to make use of the OAuth token (much faster subsequent cli calls).

**Comment by jainnikhil30** [comment]
@nicolasproton 

This is not a tower-cli bug, but this is how bash works. You would need to use "--". Something like following:

```
[niks@localhost tower-cli]$ tower-cli login -- -dash-user
Password: 
HEAD https://tower.example.com/api/o/

POST https://tower.example.com/api/v2/users/-dash-user/personal_tokens/
Data: {'application': None, 'description': 'Tower CLI', 'scope': 'write'}

{
 "id": 11, 
 "type": "o_auth2_access_token", 
 "url": "/api/v2/tokens/11/", 
 "created": "2019-03-21T09:58:16.307830Z", 
 "modified": "2019-03-21T09:58:16.335309Z", 
 "description": "Tower CLI", 
 "user": 29, 
 "refresh_token": null, 
 "application": null, 
 "expires": "3018-07-22T01:58:16.295334-08:00", 
 "scope": "write", 
 "token": "xxxxxxxx"
}
```
