### ISSUE TITLE
tower-cli does not support username with leading zero

### ISSUE THREAD

**Issue by spjssa** [ansible/tower-cli#672]
Here is an example, for valid user "008675309", which can log into the Tower web interface using the same password;
$ tower-cli credential list -u "008675309" -p ‘MyPassword'
Error: Invalid Tower authentication credentials (HTTP 401).

Other valid user, beginning with non zero succeeds ("481629847",) even when leading zero is added ("00481629847", which does not exist):

$ tower-cli credential list -u "481629847" -p 'MyPassword'
== ========================= ===============
id           name            credential_type
== ========================= ===============
71 aws-ansible-x                           5
74 ansible-vault-d                         3
42 empty-machine-credentials               1
== ========================= ===============

$ tower-cli credential list -u "00481629847" -p 'MyPassword'
== ========================= ===============
71 aws-ansible-x                           5
74 ansible-vault-d                         3
42 empty-machine-credentials               1
== ========================= ===============

It appears the username is being treated as a number somewhere along the pathway, even though the tower-cli code looks like it is a string.  Any patterns of quoting or escaping, or placing the same into .tower_cli.cfg do not make any difference.

This is a blocker for some automation we are trying to roll out, since several of the users who need to run CLI commands have the username with leading zero.  So far, we have not found any workaround for the issue.

**Comment by AlanCoding** [comment]
resolved in linked PR
