### ISSUE TITLE
job_template associate_credential does not work for extra vault credential

### ISSUE THREAD

**Issue by filip-vt** [ansible/tower-cli#707]
Using version `ansible-tower-cli-3.3.2` and in my case AWX version 3.0.1.

I wanted to add a second vault credential to a job template.

```
awx-cli job_template associate_credential --job-template myjob --credential 5
```

I get the following:

```
Error: The Tower server claims it was sent a bad request.

POST http://awxweb.service.consul/api/v2/job_templates/75/extra_credentials/
Params: None
Data: {"id": 5, "associate": true}

Response: {"error":"Extra credentials must be network or cloud."}
```

According to the docs, the `extra_credentials` endpoint was deprecated and the `credentials` endpoint within `job_templates` should be used for multiple vault support. In this case: `http://awxweb.service.consul/api/v2/job_templates/75/credentials/`. Works indeed perfectly through the AWX API.

**Comment by AlanCoding** [comment]
curious if https://github.com/ansible/tower-cli/pull/610 would work for this

**Comment by AlanCoding** [comment]
associate_credential should work with https://github.com/ansible/tower-cli/pull/741

**Comment by navdeepsachdeva** [comment]
Seems Like module "tower_job_launch" has some BUGS:
Please refer following output and suggest way around:

tower-cli receive --job_template RedHat_Job_Template
[
  {
    "asset_type": "job_template",
    "name": "RedHat_Job_Template",
    "inventory": "RedHat Inventory",
    "project": "RedHat Project",
    "playbook": "block_demo.yml",
    "survey_enabled": true,
    "become_enabled": true,
    "credential": "Redhat_Creds",
    "asset_relation": {
      "survey_spec": {
        "name": "",
        "description": "",
        "spec": [
          {
            "question_name": "Enter Package to be installed",
            "question_description": "Package Name",
            "required": true,
            "type": "text",
            "variable": "package_name",
            "min": 4,
            "max": 1024,
            "default": "httpd",
            "choices": ""
          },
          {
            "question_name": "Enter content for web file",
            "question_description": "Web File Content",
            "required": true,
            "type": "textarea",
            "variable": "web_content",
            "min": 0,
            "max": 4096,
            "default": "This is the New content of file",
            "choices": "",
            "new_question": true
          }
        ]
      },



 tower-cli job launch -J 27 --monitor
Error: The Tower server claims it was sent a bad request.

POST https://tower.lab.example.com/api/v2/job_templates/27/launch/
Params: None
Data: {}

Response: {"variables_needed_to_start":["'package_name' value missing","'web_content' value missing"]}

**Comment by navdeepsachdeva** [comment]
Seems Like module "tower_job_launch" has some BUGS:
Please refer following output and suggest way around:

tower-cli receive --job_template RedHat_Job_Template
[
  {
    "asset_type": "job_template",
    "name": "RedHat_Job_Template",
    "inventory": "RedHat Inventory",
    "project": "RedHat Project",
    "playbook": "block_demo.yml",
    "survey_enabled": true,
    "become_enabled": true,
    "credential": "Redhat_Creds",
    "asset_relation": {
      "survey_spec": {
        "name": "",
        "description": "",
        "spec": [
          {
            "question_name": "Enter Package to be installed",
            "question_description": "Package Name",
            "required": true,
            "type": "text",
            "variable": "package_name",
            "min": 4,
            "max": 1024,
            "default": "httpd",
            "choices": ""
          },
          {
            "question_name": "Enter content for web file",
            "question_description": "Web File Content",
            "required": true,
            "type": "textarea",
            "variable": "web_content",
            "min": 0,
            "max": 4096,
            "default": "This is the New content of file",
            "choices": "",
            "new_question": true
          }
        ]
      },



 tower-cli job launch -J 27 --monitor
Error: The Tower server claims it was sent a bad request.

POST https://tower.lab.example.com/api/v2/job_templates/27/launch/
Params: None
Data: {}

Response: {"variables_needed_to_start":["'package_name' value missing","'web_content' value missing"]}

**Comment by AlanCoding** [comment]
`tower-cli receive` has been replaced by AWX import/export commands. `tower-cli job launch` has been replaced by the new AWX CLI. Both of them are in the package https://pypi.org/project/awxkit/
