### ISSUE TITLE
insecure flag raises KeyError python3

### ISSUE THREAD

**Issue by wainaxman** [ansible/tower-cli#710]
# Issue
Using --insecure flag raises keyerror for python3 and ansible-tower-cli==3.3.4

Version 3.3.3 does not raise the error nor does it happen under python2.7

# Reproduction Steps
```
$ python3 -m venv test
$ source test/bin/activate
$ pip install ansible-tower-cli==3.3.4
$ tower-cli project modify x --insecure
```

# Expected Outcome (As with tower-cli=3.3.3)
```
Error: There was a network error of some kind trying to connect to Tower.
```

# Actual Outcome
```
  File "/home/hp/git/tower-cli/test/lib64/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/hp/git/tower-cli/test/lib64/python3.7/site-packages/tower_cli/api.py", line 257, in request
    r = self._make_request(method, url, args, kwargs)
  File "/home/hp/git/tower-cli/test/lib64/python3.7/site-packages/tower_cli/api.py", line 142, in _make_request
    if (settings.verify_ssl is False) or hasattr(settings, 'insecure'):
  File "/home/hp/git/tower-cli/test/lib64/python3.7/site-packages/tower_cli/conf.py", line 234, in __getattr__
    if CONFIG_PARAM_TYPE[key] == click.STRING or CONFIG_PARAM_TYPE[key] == click.Choice:
KeyError: 'insecure'
```

# Fix tower_cli/conf.py (line 50)
Add insecure flag to CONFIG_PARAM_TYPE as
```
'insecure': click.BOOL
```

**Comment by AlanCoding** [comment]
I agree with your proposed fix, the test fails you had look like they just require some test modification. Ping @jainnikhil30

**Comment by jainnikhil30** [comment]
@wainaxman @AlanCoding  yeah thats a good fix for it. Please let us know if you are able to recreate that PR with passing tests. Thanks for working on it,

**Comment by wainaxman** [comment]
Dear @AlanCoding and @jainnikhil30, i have squashed my commits and the tests are now passing. Please let me know if there's anything else to improve on my side. Thanks for your motivating words and support!
