### ISSUE TITLE
awx-cli send is failing when job templates have machine credentials

### ISSUE THREAD

**Issue by MarkRoddick** [ansible/tower-cli#716]
Tower CLI 3.3.4
AWX 5.0.0.0

### awx-cli send
The awx-cli send is returning an error when trying to send a job template with machine credentials:

```
bash-4.2# awx-cli send test.json

JOB TEMPLATE [test] ************************************************************************************************************************************************************************
Option credential is not a valid option for job_template test

PLAY RECAP *********************************************************************************************************************************************************************************
    ok=0    changed=0    warnings=0    failed=1

bash-4.2# cat test.json
[
  {
    "name": "test",
    "asset_type": "job_template",
    "project": "ansible_infra",
    "inventory": "localhost",
    "credential": "localhost",
    "asset_relation": {
       "extra_credentials": [
        "ansible"
      ],
      "notification_templates_error": [],
      "notification_templates_success": [],
      "roles": [
        {
          "team": [],
          "name": "Admin",
          "user": [
            "admin"
          ]
        },
        {
          "team": [],
          "name": "Execute",
          "user": []
        },
        {
          "team": [],
          "name": "Read",
          "user": []
        }
      ],
      "labels": [],
      "schedules": [],
      "survey_spec": {}
    },
    "playbook": "configure-reverse-proxy.yml"
  }
]

```
### awx-cli receive
The awx-cli receive command is not pulling back any machine credentials:

```
bash-4.2# awx-cli receive --job_template test
[
  {
    "name": "test",
    "asset_type": "job_template",
    "project": "ansible_infra",
    "inventory": "localhost",
    "asset_relation": {
      "extra_credentials": [
        "ansible"
      ],
      "notification_templates_error": [],
      "notification_templates_success": [],
      "roles": [
        {
          "team": [],
          "name": "Admin",
          "user": [
            "admin"
          ]
        },
        {
          "team": [],
          "name": "Execute",
          "user": []
        },
        {
          "team": [],
          "name": "Read",
          "user": []
        }
      ],
      "labels": [],
      "schedules": [],
      "survey_spec": {}
    },
    "playbook": "configure-reverse-proxy.yml"
  }
]
```

![image](https://user-images.githubusercontent.com/19282460/60441591-34747280-9c0f-11e9-9093-a6497517b3a9.png)

**Comment by mpunix** [comment]
I am seeing the same error while migrating the job_template from AWX 4.0.0 to 5.0.0. 

Option credential is not a valid option for job_template

**Comment by cbutler65** [comment]
I am seeing the same error while migrating the job_template from AWX 4.0.0 to 5.0.0.

**Comment by MarkRoddick** [comment]
https://github.com/ansible/awx/pull/3413

**Comment by AlanCoding** [comment]
Given the versions and linked PR mentioned here, I'm pretty sure this is the same thing that was discussed on the mailing list. Ping @ryanpetrello

**Comment by pypb** [comment]
Any progress on this? We're seeing the problem when trying to upgrade AWX 5.0.0 -> 6.1.0.

**Comment by cbutler65** [comment]
This command removes schedules from the export. I do something similar to remove credentials.
I then do the import
/bin/jq "del(.[].asset_relation.schedules)" </root/ansible/export/export_jobs.json >/root/ansible/export/export_jobs_new.json

**Comment by nemethk** [comment]
Adding an existing credential to a job template on AWX v6.1.0
- URL: http://<IP>/api/v2/job_templates/<JOB_TEMP_ID>/credentials/
- Method: POST
- Headers: Content-Type: application/json
- Body:
```
{
	"id": <CREDENTIAL_ID>
}
```

**Comment by mpunix** [comment]
Hi, Any progress on the fix? Still seeing on the error "Option credential is not a valid option for job_template"  on the 4.0.0 -> 6.1.0 upgrade. Any help appreciated, it just holding the upgrade and cannot progress further.

**Comment by AlanCoding** [comment]
what version of tower-cli did you try with? The most recently released version on PyPI should have the fix for this.

**Comment by mpunix** [comment]
Thank you, I installed the recent release of the tower-cli. Sorry, seems still same the error.
JOB TEMPLATE [Demo Job Template] ***********************************************************************************************************************************************
*** DETAILS: Getting the record. **********************************************
GET http://test.com/api/v2/inventories/
Params: [('name', 'Demo Inventory')]

*** DETAILS: Getting the record. **********************************************
GET http://test.com/api/v2/credentials/
Params: [('name', 'Demo Credential')]

*** DETAILS: Getting the record. **********************************************
GET http://test.com/api/v2/projects/
Params: [('name', 'Demo Project')]

Option credential is not a valid option for job_template Demo Job Template
 [WARNING]: WARNING: Relation extra_credentials is not checked

tower-cli --version ; python --version
Tower CLI 3.3.7
Python 2.7.15 :: Anaconda, Inc.

IMAGE                      
ansible/awx_task:5.0.0     
ansible/awx_web:5.0.0      
memcached:alpine           
ansible/awx_rabbitmq:3.7.4 
postgres:9.6

**Comment by mpunix** [comment]
Thank you, I installed the recent release of the tower-cli. Sorry, seems still same the error. Exported and try importing the template using tower-cli.

JOB TEMPLATE [gateway_dev] *******************************************************************************************************************************************
*** DETAILS: Getting the record. **********************************************
GET http://test.com/api/v2/inventories/
Params: [('name', 'inv_dev')]

*** DETAILS: Getting the record. **********************************************
GET http://test.com/api/v2/credentials/
Params: [('name', 'Machine: User ssh key')]

*** DETAILS: Getting the record. **********************************************
GET http://test.com/api/v2/projects/
Params: [('name', 'prj_develop')]

Option credential is not a valid option for job_template gateway_dev
*** DETAILS: Getting records. *************************************************
GET http://test.com/api/v2/teams/
Params: [('name', 'Application Support')]

*** DETAILS: Getting the record. **********************************************
GET http://test.com/api/v2/credentials/
Params: [('name', 'Machine: User ssh key')]



tower-cli --version ; python --version
Tower CLI 3.3.7
Python 2.7.15 :: Anaconda, Inc.

IMAGE                      
ansible/awx_task:5.0.0     
ansible/awx_web:5.0.0      
memcached:alpine           
ansible/awx_rabbitmq:3.7.4 
postgres:9.6

**Comment by AlanCoding** [comment]
what version did you receive with vs what version did you send to?

I you are doing cross-version stuff, there might be a need for manipulation of the file.

**Comment by mpunix** [comment]
I tried with receive and send with tower-cli 3.3.7 of job_template but I already send project,credentials,team using tower-cli3.3.4 as waiting for fix. I will try all the tasks from start using 3.3.7 to isolate the issue.

Thank you.

**Comment by mpunix** [comment]
I did reinstall and receive data from 4.0 and when I send to 5.0, it seems still this credential error. Here is the Demo template. I removed the "credential": "Demo Credential", line using SED Unix tool and able to import to 5.0. Not sure if any miss anything on the export/import, will see any other people came across the same error.

Migration steps:
1. Export from AWX 4.0
2. Install AWX 5.0
3. Import to AWX 5.0, Template fails.

Tower-cli version: Tower CLI 3.3.7 (same version used for export and import the data0

[
  {
    "credential": "Demo Credential",
    "name": "Demo Job Template",
    "asset_relation": {
      "notification_templates_error": [],
      "notification_templates_success": [],
      "roles": [
        {
          "team": [],
          "name": "Admin",
          "user": []
        },
        {
          "team": [],
          "name": "Execute",
          "user": []
        },
        {
          "team": [],
          "name": "Read",
          "user": []
        }
      ],
      "labels": [],
      "schedules": [],
      "credentials": [
        "Demo Credential"
      ],
      "survey_spec": {}
    },
    "project": "Demo Project",
    "inventory": "Demo Inventory",
    "asset_type": "job_template",
    "playbook": "hello_world.yml"
  }
]

**Comment by wrsuarez** [comment]
Also having this issue doing a receive from 3.0.0 and send to 7.0.0

**Comment by mpunix** [comment]
Same error, as a workaround i deleted the credential entry. it works for me on the send (import on 8.0.0).

![image](https://user-images.githubusercontent.com/34629039/70458655-718c3d00-1aaa-11ea-85c3-dce33eb16d7b.png)

**Comment by tgates81** [comment]
I'm also having this issue between 3.3.7 send and receive. Any progress on this or viable work arounds other than removing vault_credential and credential from the imports?

**Comment by AlanCoding** [comment]
vault_credential should probably be made to work with

https://github.com/ansible/tower-cli/pull/745

**Comment by tgates81** [comment]
Am I reading correctly both credential and vault_credential could be thrown into credentials list and it would work?

**Comment by AlanCoding** [comment]
for recent-enough versions, yes

but it's the cross-version compatibility that kills us with that. If you had exported data, you might do alright copying vault credentials to the credentials list.

**Comment by tgates81** [comment]
Hi Alan,
   What version are you recommending here? 3.3.7 is not recognizing 'credentials'.

Thank you

**Comment by AlanCoding** [comment]
From https://github.com/ansible/tower-cli/pull/741, 3.3.7 with a recent AWX should send credentials

**Comment by tgates81** [comment]
Got it now. Didn't realize AWX version played a role in this, that explains the issues despite having 3.3.7 tower-cli.
Also didn't realize credentials already existed in my legacy receive dump. Once I removed credential and vault_credential, as long as they exist in credentials, it worked fine.

**Comment by tgates81** [comment]
BTW anyone looking to purge credential and vault_credential from tower_receive this works:

      - name: "Prune legacy credential and vault_credential definitions in favor of credentials"
        set_fact:                                                               
          new_jts: >                                                            
            {%- set jinja_dict = {} -%}                                         
            {%- for k, v in item.items() -%}                                    
              {%- if k not in ignore_keys -%}                                   
                {%- set ignore = jinja_dict.update({k: v}) -%}                  
              {%- endif -%}                                                     
            {%- endfor -%}                                                      
            {{ new_jts | default([]) + [ jinja_dict ] }}                        
        with_items: "{{ job_templates.assets }}"                                
        vars:                                                                   
          ignore_keys:                                                          
            - "credential"                                                      
            - "vault_credential"


I'm not a fan of embedded jinja but I couldn't come up with a better way..
