### ISSUE TITLE
Failed to Launch Template with Survey Variables 

### ISSUE THREAD

**Issue by navdeepsachdeva** [ansible/tower-cli#758]
Failed to Launch Template with Survey Variables with both Module tower_job_launch and command (Below Output)

tower-cli receive --job_template RedHat_Job_Template
[
  {
    "asset_type": "job_template",
    "name": "RedHat_Job_Template",
    "inventory": "RedHat Inventory",
    "project": "RedHat Project",
    "playbook": "block_demo.yml",
    "survey_enabled": true,
    "become_enabled": true,
    "credential": "Redhat_Creds",
    "asset_relation": {
      "survey_spec": {
        "name": "",
        "description": "",
        "spec": [
          {
            "question_name": "Enter Package to be installed",
            "question_description": "Package Name",
            "required": true,
            "type": "text",
            "variable": "package_name",
            "min": 4,
            "max": 1024,
            "default": "httpd",
            "choices": ""
          },
          {
            "question_name": "Enter content for web file",
            "question_description": "Web File Content",
            "required": true,
            "type": "textarea",
            "variable": "web_content",
            "min": 0,
            "max": 4096,
            "default": "This is the New content of file",
            "choices": "",
            "new_question": true
          }
        ]
      },
      "notification_templates_error": [
        "Notify Stakeholders"
      ],
      "notification_templates_success": [
        "Notify Stakeholders"
      ],
      "extra_credentials": [],
      "schedules": [],
      "labels": [],
      "roles": [
        {
          "name": "Admin",
          "user": [
            "admin"
          ],
          "team": [
            "Development"
          ]
        },
        {
          "name": "Execute",
          "user": [],
          "team": [
            "Production"
          ]
        },
        {
          "name": "Read",
          "user": [],
          "team": []
        }
      ]
    }
  }

tower-cli job launch -J 27 --monitor
Error: The Tower server claims it was sent a bad request.

POST https://tower.lab.example.com/api/v2/job_templates/27/launch/
Params: None
Data: {}

Response: {"variables_needed_to_start":["'package_name' value missing","'web_content' value missing"]}

**Comment by wenottingham** [comment]
a) this repo is no longer maintained, see https://github.com/ansible/tower-cli/blob/master/README.rst
b) that error tells you the exact error you made

**Comment by navdeepsachdeva** [comment]
If you see job template above error, it says parameters are provided via survey. If you run this template(as it is) via ansible tower in GUI it works, but via module or command line tower-cli it fails. I have put this after investigating
