### ISSUE TITLE
Force on exists gone when creating a project?

### ISSUE THREAD

**Issue by mikeycmccarthy** [ansible/tower-cli#88]
Hi,

It seems between 2.3.0 and 2.1.1 that force-on-exists has disappeared as an option when creating a project. Is this deliberate?

Thanks
Michael

**Comment by AlanCoding** [comment]
> Is this deliberate?

No. This is a straight-forward bug brought about by other development decisions. Thanks for bringing it to our attention. We can get that straightened out with the next release.
