### ISSUE TITLE
msg: No package matching 'ansible-tower' is available (ubuntu14.04 on AWS)

### ISSUE THREAD

**Issue by maxidea-com** [ansible/tower-cli#92]
Hi 

I got following error when I setup tower (ansible-tower-setup-2.4.0) on a ubuntu14.04: 

/////////////////////
TASK: [packages_ubuntu | Install Tower package with the apt module.] ********** 
failed: [localhost] => {"failed": true}
msg: No package matching 'ansible-tower' is available

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ubuntu/install.retry

localhost                  : ok=37   changed=7    unreachable=0    failed=1   
////////////////////

Do you have any idea about this?

I have already do following setting for my ubuntu14.04 as quickinstall:

///////////////////
1.7.1. Configure access to the repository for Ansible with Ubuntu 12.04 and Ubuntu 14.04:
As the root user, configure Ansible PPA:
root@localhost:~$ apt-get install software-properties-common
root@localhost:~$ apt-add-repository ppa:ansible/ansible
1.7.2. Install Ansible on Ubuntu 12.04 and Ubuntu 14.04:
root@localhost:~$ apt-get update
root@localhost:~$ apt-get install ansible
///////////////////

Thanks&Regards,
Simon

**Comment by maxidea-com** [comment]
I have fixed this issue due to the new version tower was released. ( I just download the latest.gz at yesterday but it was included a old version 2.4.0) 
So this error was fixed after I download the new latest.gz today.... (v2.4.1)

FYI: http://lost-and-found-narihiro.blogspot.com/2015/02/install-ansible-tower-on-ubuntu-1404.html

**Comment by jlaska** [comment]
Thanks for reporting this issue @maxidea-com.  I'm afraid this isn't the right place for reporting issues with the product Ansible Tower.  While the reported issue has been resolved, I recommend using support@ansible.com to report issues in the future.  Thanks!

**Comment by AlanCoding** [comment]
You can also go about support requests through the portal at https://support.ansible.com/hc/en-us

I will go ahead and close this issue, since there's nothing to do for tower-cli.
