### ISSUE TITLE
extra vars are not passed to the api properly

### ISSUE THREAD

**Issue by bennojoy** [ansible/tower-cli#96]
in 2.3 if we launch a job with extra args, the extra args are not visible in the job. I think it is because the json is malformed when passed to the api and hence the api ignores the extra args and takes the default in the job template.

**Comment by bennojoy** [comment]
i think this only happens to 2.4.1 version of tower. didnt test yet

**Comment by AlanCoding** [comment]
Thank you for bringing this to our attention. My testing approach would follow this type of framework:

> tower-cli job launch --job-template="Hello World Debug" --job-explanation="launched by CLI" --extra-vars "a=3" -v

Somewhere in the output, we will be looking for the 

```
*** DETAILS: Launching the job. ***********************************************
POST https://arominger-0405ce70.eng.ansible.com/api/v1/job_templates/14/launch/
Data: {'extra_vars': 'a=3', 'job_explanation': 'launched by CLI'}
```

Doing this right now, here is my info:
- Tower version 2.4.1
- tower-cli version 2.3.0

The output above shows the extra vars in the request. On to your issue, we check the job record from Tower.

> tower-cli job get 7 --format=json

With up-to-date testing, I do find `"extra_vars": "{}",` within the output from this. Testing different formatting of the extra_vars doesn't change this behavior. So you are right, the data isn't getting accepted by Tower, and I am going to continue to try hunting this down.

**Comment by AlanCoding** [comment]
After testing this further, I think I have a better idea of the behavior you've alluded to, and if I am correct I can push a fix.

Firstly, here is an example of a valid manual submission through the api browser. You may have inputted something like this in your testing `{"extra_vars":{"z":7,"x":9}}`. Here is an example of an input that works, being passed from tower-cli to the server `{'extra_vars': '{"y": 2, "z": 4}'}`. FYI, this will not work if you manually enter it into the api browser. This will be produced by tower-cli if you run it with flags formatted like this `--extra-vars z=4 --extra-vars y=2`. So again, that case works. But we don't want to have to use 2 flags. Say you want to combine these into one extra-vars flag. That would correctly work with the syntax `--extra-vars '{"y": 2, "z": 4}'`. However, I see how this is very fragile syntax.

Also, I had been under the impression that Tower would accept key=value pairs or yaml on its own, and thus it would be best to pass on extra-vars as-is and let Tower sort it out. This is how tower-cli had always worked before 2.3.0 anyway. Right now, I can not get it to accept any type of input other than json, and this is a problem. As it is, we don't touch the user input if there are not multiple sources of extra-vars to combine, and I would claim that is the source of the problems you have seen. To change this, we would simply disable the special case and always re-parse the user input.

**Comment by AlanCoding** [comment]
You can try it with the changes I discussed by the following commands:

```bash
git clone https://github.com/AlanCoding/tower-cli.git
cd tower-cli
sudo python setup.py install
```

Then retrace your steps to reproduce the issue and see if it is fixed.

**Comment by jlaska** [comment]
Alan, you are correct.  Tower is incapable of parsing key=value pairs. Tower accepts *only* JSON extra vars.

**Comment by haimari** [comment]
Does not work:
/usr/bin/tower-cli job launch --job-template=82 --extra-vars build=xxx
Works:
/usr/bin/tower-cli job launch --job-template=82 --extra-vars '{"build": xxx}'

**Comment by haimari** [comment]
OK This works:
/usr/bin/tower-cli job launch --job-template=8 --extra-vars '{"build": '${BUILD_NUMBER}'}'

**Comment by teewhey** [comment]
Looked good so far using the updated code.

Git log 
commit ac52427f7f6e750122c4e150d4cd90dc446173fe
Author: Alan R <alan.rominger@gmail.com>
Date:   Thu Nov 26 22:09:49 2015 -0500

    For release 2.3.1

    Carry through cascade of changes in tests and related functionality
    from the change in how single-source extra_vars are handled
